threads: threads.rs
	rustc --extern platform=../../../tests/rust/unverified/platform/target/debug/libplatform.rlib -L dependency=../../../tests/rust/unverified/platform/target/debug/deps threads.rs

fractions0: fractions0.rs
	rustc --extern platform=../../../tests/rust/unverified/platform/target/debug/libplatform.rlib -L dependency=../../../tests/rust/unverified/platform/target/debug/deps fractions0.rs

fractions: fractions.rs
	rustc --extern platform=../../../tests/rust/unverified/platform/target/debug/libplatform.rlib -L dependency=../../../tests/rust/unverified/platform/target/debug/deps fractions.rs
