// This file is autogenerated by VeriFast to check the contract of the program's main method.
class MainClassTest {
    static void test(String[] args) throws Throwable /*@ ensures true; @*/
        //@ requires class_init_token(chat.Program.class);
        //@ ensures true;
    {
        chat.Program.main(args);
    }
}
