FROM --platform=linux/amd64 mcr.microsoft.com/devcontainers/base:ubuntu-22.04

# Mark the workspace safe for every user in the image.
RUN git config --system --add safe.directory /workspaces/verifast
