#ifndef POLARSSL_SIZES
#define POLARSSL_SIZES

#define POLARSSL_CHAR_SIZE_OF_HAVEGE_STATE 36880
#define POLARSSL_CHAR_SIZE_OF_AES_CONTEXT 280
#define POLARSSL_AES_CIPHER_ID 2
#define POLARSSL_CHAR_SIZE_OF_GCM_CONTEXT 388
#define POLARSSL_PK_RSA_TYPE 1
#define POLARSSL_MD_NONE 0

#endif

