open Printf

let () =
  if Array.length Sys.argv <> 2 then begin
    prerr_endline "Syntax error. Usage: java_card_applet mypackage.MyApplet";
    exit 1
  end;
  let appletClass = Sys.argv.(1) in
  printf "// This file is autogenerated by VeriFast to check the contract of the applet's install method.\n";
  printf "\n";
  printf "import javacard.framework.*;\n";
  printf "\n";
  printf "class JavaCardAppletTest {\n";
  printf "    static void test(byte[] buffer, short offset, byte length)";
  printf "        //@ requires array_slice(buffer, offset, length, _) &*& system() &*& class_init_token(%s.class);\n" appletClass;
  printf "        //@ ensures true;\n";
  printf "    {\n";
  printf "        %s.install(buffer, offset, length);\n" appletClass;
  printf "    }\n";
  printf "}\n"
