open Printf

let () =
  if Array.length Sys.argv <> 2 then begin
    prerr_endline "Syntax error. Usage: main_class mymainpackage.MyMainClass";
    exit 1
  end;
  let mainClass = Sys.argv.(1) in
  printf "// This file is autogenerated by VeriFast to check the contract of the program's main method.\n";
  printf "class MainClassTest {\n";
  printf "    static void test(String[] args) throws Throwable /*@ ensures true; @*/\n";
  printf "        //@ requires true;\n";
  printf "        //@ ensures true;\n";
  printf "    {\n";
  printf "        %s.main(args);\n" mainClass;
  printf "    }\n";
  printf "}\n"
