/* linemarks.c generated by valac 0.22.1, the Vala compiler
 * generated from linemarks.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <string.h>
#include <gtksourceview/gtksourceview.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PIXBUF_WITH_CACHE (pixbuf_with_cache_get_type ())
#define PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCache))
#define PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))
#define IS_PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PIXBUF_WITH_CACHE))
#define IS_PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PIXBUF_WITH_CACHE))
#define PIXBUF_WITH_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))

typedef struct _PixbufWithCache PixbufWithCache;
typedef struct _PixbufWithCacheClass PixbufWithCacheClass;
typedef struct _PixbufWithCachePrivate PixbufWithCachePrivate;
#define _pixbuf_with_cache_unref0(var) ((var == NULL) ? NULL : (var = (pixbuf_with_cache_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecPixbufWithCache ParamSpecPixbufWithCache;

#define TYPE_LINE_MARK (line_mark_get_type ())
#define LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARK, LineMark))
#define LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARK, LineMarkClass))
#define IS_LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARK))
#define IS_LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARK))
#define LINE_MARK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARK, LineMarkClass))

typedef struct _LineMark LineMark;
typedef struct _LineMarkClass LineMarkClass;
typedef struct _LineMarkPrivate LineMarkPrivate;
typedef struct _ParamSpecLineMark ParamSpecLineMark;

#define TYPE_LINE_MARKS_TABLE (line_marks_table_get_type ())
#define LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTable))
#define LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))
#define IS_LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_TABLE))
#define IS_LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_TABLE))
#define LINE_MARKS_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))

typedef struct _LineMarksTable LineMarksTable;
typedef struct _LineMarksTableClass LineMarksTableClass;
typedef struct _LineMarksTablePrivate LineMarksTablePrivate;
#define _line_mark_unref0(var) ((var == NULL) ? NULL : (var = (line_mark_unref (var), NULL)))

#define TYPE_LINE_MARKS_RENDERER (line_marks_renderer_get_type ())
#define LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRenderer))
#define LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))
#define IS_LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_RENDERER))
#define IS_LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_RENDERER))
#define LINE_MARKS_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))

typedef struct _LineMarksRenderer LineMarksRenderer;
typedef struct _LineMarksRendererClass LineMarksRendererClass;
typedef struct _LineMarksRendererPrivate LineMarksRendererPrivate;
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

struct _PixbufWithCache {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PixbufWithCachePrivate * priv;
	PixbufWithCache* next;
	GdkPixbuf* original;
	gint scaledSize;
	GdkPixbuf* scaled;
};

struct _PixbufWithCacheClass {
	GTypeClass parent_class;
	void (*finalize) (PixbufWithCache *self);
};

struct _ParamSpecPixbufWithCache {
	GParamSpec parent_instance;
};

struct _LineMark {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LineMarkPrivate * priv;
	GtkTextMark* textMark;
	PixbufWithCache* pixbuf;
	gint line;
	gint column;
};

struct _LineMarkClass {
	GTypeClass parent_class;
	void (*finalize) (LineMark *self);
};

struct _ParamSpecLineMark {
	GParamSpec parent_instance;
};

struct _LineMarksTable {
	GObject parent_instance;
	LineMarksTablePrivate * priv;
	LineMark** lineMarks;
	gint lineMarks_length1;
	gint _lineMarks_size_;
	gint lineHeight;
	gint rendererWidth;
	GtkTextBuffer* lastBuffer;
	gint lastLineNumber;
	gint nextIndex;
	gint lineNumber;
};

struct _LineMarksTableClass {
	GObjectClass parent_class;
};

struct _LineMarksTablePrivate {
	PixbufWithCache* pixbufCache;
	gboolean sorted;
};

struct _LineMarksRenderer {
	GtkCellRenderer parent_instance;
	LineMarksRendererPrivate * priv;
};

struct _LineMarksRendererClass {
	GtkCellRendererClass parent_class;
};

struct _LineMarksRendererPrivate {
	LineMarksTable* table;
	GtkSourceGutter* gutter;
};


static gpointer pixbuf_with_cache_parent_class = NULL;
static gpointer line_mark_parent_class = NULL;
static gpointer line_marks_table_parent_class = NULL;
static gpointer line_marks_renderer_parent_class = NULL;

gpointer pixbuf_with_cache_ref (gpointer instance);
void pixbuf_with_cache_unref (gpointer instance);
GParamSpec* param_spec_pixbuf_with_cache (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_pixbuf_with_cache (GValue* value, gpointer v_object);
void value_take_pixbuf_with_cache (GValue* value, gpointer v_object);
gpointer value_get_pixbuf_with_cache (const GValue* value);
GType pixbuf_with_cache_get_type (void) G_GNUC_CONST;
enum  {
	PIXBUF_WITH_CACHE_DUMMY_PROPERTY
};
PixbufWithCache* pixbuf_with_cache_new (PixbufWithCache* next, GdkPixbuf* original);
PixbufWithCache* pixbuf_with_cache_construct (GType object_type, PixbufWithCache* next, GdkPixbuf* original);
GdkPixbuf* pixbuf_with_cache_get_at_size (PixbufWithCache* self, gint size);
static void pixbuf_with_cache_finalize (PixbufWithCache* obj);
gpointer line_mark_ref (gpointer instance);
void line_mark_unref (gpointer instance);
GParamSpec* param_spec_line_mark (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_line_mark (GValue* value, gpointer v_object);
void value_take_line_mark (GValue* value, gpointer v_object);
gpointer value_get_line_mark (const GValue* value);
GType line_mark_get_type (void) G_GNUC_CONST;
enum  {
	LINE_MARK_DUMMY_PROPERTY
};
LineMark* line_mark_new (GtkTextMark* textMark, PixbufWithCache* pixbuf);
LineMark* line_mark_construct (GType object_type, GtkTextMark* textMark, PixbufWithCache* pixbuf);
void line_mark_update_line_column_cache (LineMark* self);
static void line_mark_finalize (LineMark* obj);
GType line_marks_table_get_type (void) G_GNUC_CONST;
#define LINE_MARKS_TABLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LINE_MARKS_TABLE, LineMarksTablePrivate))
enum  {
	LINE_MARKS_TABLE_DUMMY_PROPERTY
};
static PixbufWithCache* line_marks_table_get_pixbuf_with_cache (LineMarksTable* self, GdkPixbuf* pixbuf);
void line_marks_table_clear (LineMarksTable* self);
static void line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self);
static gint line_marks_table_compare_line_marks (LineMark** m1, LineMark** m2);
static void line_marks_table_sort_line_marks (LineMarksTable* self);
static gint _line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a, gconstpointer b, gpointer self);
void line_marks_table_add_line_mark (LineMarksTable* self, GtkTextMark* textMark, GdkPixbuf* pixbuf);
static void _vala_array_add1 (LineMark*** array, int* length, int* size, LineMark* value);
void line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self, GtkTextBuffer* buffer, gint line, gint offset, GdkPixbuf* pixbuf);
static gint line_marks_table_measure_line_height (LineMarksTable* self, GtkSourceView* view);
static gint line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self, GtkTextBuffer* buffer);
static void line_marks_table_size_func (LineMarksTable* self, GtkSourceGutter* gutter, GtkCellRenderer* renderer);
static void line_marks_table_data_func (LineMarksTable* self, GtkSourceGutter* gutter, GtkCellRenderer* renderer, gint lineNumber, gboolean currentLine);
void line_marks_table_show_in_source_view (LineMarksTable* self, GtkSourceView* sourceView);
GType line_marks_renderer_get_type (void) G_GNUC_CONST;
LineMarksRenderer* line_marks_renderer_new (LineMarksTable* table, GtkSourceGutter* gutter);
LineMarksRenderer* line_marks_renderer_construct (GType object_type, LineMarksTable* table, GtkSourceGutter* gutter);
static void _line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter, GtkCellRenderer* cell, gpointer self);
static void _line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter, GtkCellRenderer* cell, gint line_number, gboolean current_line, gpointer self);
LineMarksTable* line_marks_table_new (void);
LineMarksTable* line_marks_table_construct (GType object_type);
static void line_marks_table_finalize (GObject* obj);
#define LINE_MARKS_RENDERER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LINE_MARKS_RENDERER, LineMarksRendererPrivate))
enum  {
	LINE_MARKS_RENDERER_DUMMY_PROPERTY
};
static void line_marks_renderer_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height);
static void line_marks_renderer_real_render (GtkCellRenderer* base, GdkWindow* window, GtkWidget* widget, GdkRectangle* background_area, GdkRectangle* cell_area, GdkRectangle* expose_area, GtkCellRendererState flags);
static void line_marks_renderer_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _pixbuf_with_cache_ref0 (gpointer self) {
	return self ? pixbuf_with_cache_ref (self) : NULL;
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


PixbufWithCache* pixbuf_with_cache_construct (GType object_type, PixbufWithCache* next, GdkPixbuf* original) {
	PixbufWithCache* self = NULL;
	PixbufWithCache* _tmp0_ = NULL;
	PixbufWithCache* _tmp1_ = NULL;
	GdkPixbuf* _tmp2_ = NULL;
	GdkPixbuf* _tmp3_ = NULL;
	g_return_val_if_fail (original != NULL, NULL);
	self = (PixbufWithCache*) g_type_create_instance (object_type);
	_tmp0_ = next;
	_tmp1_ = _pixbuf_with_cache_ref0 (_tmp0_);
	_pixbuf_with_cache_unref0 (self->next);
	self->next = _tmp1_;
	_tmp2_ = original;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->original);
	self->original = _tmp3_;
	self->scaledSize = -1;
	_g_object_unref0 (self->scaled);
	self->scaled = NULL;
	return self;
}


PixbufWithCache* pixbuf_with_cache_new (PixbufWithCache* next, GdkPixbuf* original) {
	return pixbuf_with_cache_construct (TYPE_PIXBUF_WITH_CACHE, next, original);
}


GdkPixbuf* pixbuf_with_cache_get_at_size (PixbufWithCache* self, gint size) {
	GdkPixbuf* result = NULL;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	GdkPixbuf* _tmp7_ = NULL;
	GdkPixbuf* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->scaledSize;
	_tmp1_ = size;
	if (_tmp0_ != _tmp1_) {
		GdkPixbuf* _tmp2_ = NULL;
		gint _tmp3_ = 0;
		gint _tmp4_ = 0;
		GdkPixbuf* _tmp5_ = NULL;
		gint _tmp6_ = 0;
		_tmp2_ = self->original;
		_tmp3_ = size;
		_tmp4_ = size;
		_tmp5_ = gdk_pixbuf_scale_simple (_tmp2_, _tmp3_, _tmp4_, GDK_INTERP_BILINEAR);
		_g_object_unref0 (self->scaled);
		self->scaled = _tmp5_;
		_tmp6_ = size;
		self->scaledSize = _tmp6_;
	}
	_tmp7_ = self->scaled;
	_tmp8_ = _g_object_ref0 (_tmp7_);
	result = _tmp8_;
	return result;
}


static void value_pixbuf_with_cache_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_pixbuf_with_cache_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		pixbuf_with_cache_unref (value->data[0].v_pointer);
	}
}


static void value_pixbuf_with_cache_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = pixbuf_with_cache_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_pixbuf_with_cache_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_pixbuf_with_cache_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		PixbufWithCache* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = pixbuf_with_cache_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_pixbuf_with_cache_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	PixbufWithCache** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = pixbuf_with_cache_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_pixbuf_with_cache (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecPixbufWithCache* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PIXBUF_WITH_CACHE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_pixbuf_with_cache (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE), NULL);
	return value->data[0].v_pointer;
}


void value_set_pixbuf_with_cache (GValue* value, gpointer v_object) {
	PixbufWithCache* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		pixbuf_with_cache_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}


void value_take_pixbuf_with_cache (GValue* value, gpointer v_object) {
	PixbufWithCache* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}


static void pixbuf_with_cache_class_init (PixbufWithCacheClass * klass) {
	pixbuf_with_cache_parent_class = g_type_class_peek_parent (klass);
	PIXBUF_WITH_CACHE_CLASS (klass)->finalize = pixbuf_with_cache_finalize;
}


static void pixbuf_with_cache_instance_init (PixbufWithCache * self) {
	self->ref_count = 1;
}


static void pixbuf_with_cache_finalize (PixbufWithCache* obj) {
	PixbufWithCache * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PIXBUF_WITH_CACHE, PixbufWithCache);
	_pixbuf_with_cache_unref0 (self->next);
	_g_object_unref0 (self->original);
	_g_object_unref0 (self->scaled);
}


GType pixbuf_with_cache_get_type (void) {
	static volatile gsize pixbuf_with_cache_type_id__volatile = 0;
	if (g_once_init_enter (&pixbuf_with_cache_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_pixbuf_with_cache_init, value_pixbuf_with_cache_free_value, value_pixbuf_with_cache_copy_value, value_pixbuf_with_cache_peek_pointer, "p", value_pixbuf_with_cache_collect_value, "p", value_pixbuf_with_cache_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PixbufWithCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pixbuf_with_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PixbufWithCache), 0, (GInstanceInitFunc) pixbuf_with_cache_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType pixbuf_with_cache_type_id;
		pixbuf_with_cache_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PixbufWithCache", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&pixbuf_with_cache_type_id__volatile, pixbuf_with_cache_type_id);
	}
	return pixbuf_with_cache_type_id__volatile;
}


gpointer pixbuf_with_cache_ref (gpointer instance) {
	PixbufWithCache* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void pixbuf_with_cache_unref (gpointer instance) {
	PixbufWithCache* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PIXBUF_WITH_CACHE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


LineMark* line_mark_construct (GType object_type, GtkTextMark* textMark, PixbufWithCache* pixbuf) {
	LineMark* self = NULL;
	GtkTextMark* _tmp0_ = NULL;
	GtkTextMark* _tmp1_ = NULL;
	PixbufWithCache* _tmp2_ = NULL;
	PixbufWithCache* _tmp3_ = NULL;
	g_return_val_if_fail (textMark != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	self = (LineMark*) g_type_create_instance (object_type);
	_tmp0_ = textMark;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->textMark);
	self->textMark = _tmp1_;
	_tmp2_ = pixbuf;
	_tmp3_ = _pixbuf_with_cache_ref0 (_tmp2_);
	_pixbuf_with_cache_unref0 (self->pixbuf);
	self->pixbuf = _tmp3_;
	return self;
}


LineMark* line_mark_new (GtkTextMark* textMark, PixbufWithCache* pixbuf) {
	return line_mark_construct (TYPE_LINE_MARK, textMark, pixbuf);
}


void line_mark_update_line_column_cache (LineMark* self) {
	GtkTextIter iter = {0};
	GtkTextMark* _tmp0_ = NULL;
	GtkTextBuffer* _tmp1_ = NULL;
	GtkTextMark* _tmp2_ = NULL;
	GtkTextIter _tmp3_ = {0};
	gint _tmp4_ = 0;
	gint _tmp5_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->textMark;
	_tmp1_ = gtk_text_mark_get_buffer (_tmp0_);
	_tmp2_ = self->textMark;
	gtk_text_buffer_get_iter_at_mark (_tmp1_, &_tmp3_, _tmp2_);
	iter = _tmp3_;
	_tmp4_ = gtk_text_iter_get_line (&iter);
	self->line = _tmp4_;
	_tmp5_ = gtk_text_iter_get_line_offset (&iter);
	self->column = _tmp5_;
}


static void value_line_mark_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_line_mark_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		line_mark_unref (value->data[0].v_pointer);
	}
}


static void value_line_mark_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = line_mark_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_line_mark_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_line_mark_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		LineMark* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = line_mark_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_line_mark_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	LineMark** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = line_mark_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_line_mark (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecLineMark* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_LINE_MARK), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_line_mark (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK), NULL);
	return value->data[0].v_pointer;
}


void value_set_line_mark (GValue* value, gpointer v_object) {
	LineMark* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		line_mark_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}


void value_take_line_mark (GValue* value, gpointer v_object) {
	LineMark* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}


static void line_mark_class_init (LineMarkClass * klass) {
	line_mark_parent_class = g_type_class_peek_parent (klass);
	LINE_MARK_CLASS (klass)->finalize = line_mark_finalize;
}


static void line_mark_instance_init (LineMark * self) {
	self->ref_count = 1;
}


static void line_mark_finalize (LineMark* obj) {
	LineMark * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARK, LineMark);
	_g_object_unref0 (self->textMark);
	_pixbuf_with_cache_unref0 (self->pixbuf);
}


GType line_mark_get_type (void) {
	static volatile gsize line_mark_type_id__volatile = 0;
	if (g_once_init_enter (&line_mark_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_line_mark_init, value_line_mark_free_value, value_line_mark_copy_value, value_line_mark_peek_pointer, "p", value_line_mark_collect_value, "p", value_line_mark_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (LineMarkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_mark_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMark), 0, (GInstanceInitFunc) line_mark_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType line_mark_type_id;
		line_mark_type_id = g_type_register_fundamental (g_type_fundamental_next (), "LineMark", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&line_mark_type_id__volatile, line_mark_type_id);
	}
	return line_mark_type_id__volatile;
}


gpointer line_mark_ref (gpointer instance) {
	LineMark* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void line_mark_unref (gpointer instance) {
	LineMark* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		LINE_MARK_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static PixbufWithCache* line_marks_table_get_pixbuf_with_cache (LineMarksTable* self, GdkPixbuf* pixbuf) {
	PixbufWithCache* result = NULL;
	PixbufWithCache* cache = NULL;
	PixbufWithCache* _tmp0_ = NULL;
	PixbufWithCache* _tmp1_ = NULL;
	PixbufWithCache* _tmp11_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	_tmp0_ = self->priv->pixbufCache;
	_tmp1_ = _pixbuf_with_cache_ref0 (_tmp0_);
	cache = _tmp1_;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		PixbufWithCache* _tmp3_ = NULL;
		gboolean _tmp7_ = FALSE;
		PixbufWithCache* _tmp8_ = NULL;
		PixbufWithCache* _tmp9_ = NULL;
		PixbufWithCache* _tmp10_ = NULL;
		_tmp3_ = cache;
		if (_tmp3_ != NULL) {
			PixbufWithCache* _tmp4_ = NULL;
			GdkPixbuf* _tmp5_ = NULL;
			GdkPixbuf* _tmp6_ = NULL;
			_tmp4_ = cache;
			_tmp5_ = _tmp4_->original;
			_tmp6_ = pixbuf;
			_tmp2_ = _tmp5_ != _tmp6_;
		} else {
			_tmp2_ = FALSE;
		}
		_tmp7_ = _tmp2_;
		if (!_tmp7_) {
			break;
		}
		_tmp8_ = cache;
		_tmp9_ = _tmp8_->next;
		_tmp10_ = _pixbuf_with_cache_ref0 (_tmp9_);
		_pixbuf_with_cache_unref0 (cache);
		cache = _tmp10_;
	}
	_tmp11_ = cache;
	if (_tmp11_ == NULL) {
		PixbufWithCache* _tmp12_ = NULL;
		GdkPixbuf* _tmp13_ = NULL;
		PixbufWithCache* _tmp14_ = NULL;
		PixbufWithCache* _tmp15_ = NULL;
		PixbufWithCache* _tmp16_ = NULL;
		_tmp12_ = self->priv->pixbufCache;
		_tmp13_ = pixbuf;
		_tmp14_ = pixbuf_with_cache_new (_tmp12_, _tmp13_);
		_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
		self->priv->pixbufCache = _tmp14_;
		_tmp15_ = self->priv->pixbufCache;
		_tmp16_ = _pixbuf_with_cache_ref0 (_tmp15_);
		result = _tmp16_;
		_pixbuf_with_cache_unref0 (cache);
		return result;
	} else {
		result = cache;
		return result;
	}
	_pixbuf_with_cache_unref0 (cache);
}


void line_marks_table_clear (LineMarksTable* self) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = 0;
	self->lineMarks = g_renew (LineMark*, self->lineMarks, 0);
	(_tmp0_ > self->lineMarks_length1) ? memset (self->lineMarks + self->lineMarks_length1, 0, sizeof (LineMark*) * (_tmp0_ - self->lineMarks_length1)) : NULL;
	self->lineMarks_length1 = _tmp0_;
	self->_lineMarks_size_ = _tmp0_;
}


static gpointer _line_mark_ref0 (gpointer self) {
	return self ? line_mark_ref (self) : NULL;
}


static void line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self) {
	g_return_if_fail (self != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_ = FALSE;
				gint _tmp3_ = 0;
				LineMark** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				LineMark* mark = NULL;
				LineMark** _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				LineMark* _tmp7_ = NULL;
				LineMark* _tmp8_ = NULL;
				LineMark* _tmp9_ = NULL;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->lineMarks;
				_tmp4__length1 = self->lineMarks_length1;
				if (!(_tmp3_ < _tmp4__length1)) {
					break;
				}
				_tmp5_ = self->lineMarks;
				_tmp5__length1 = self->lineMarks_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = _line_mark_ref0 (_tmp7_);
				mark = _tmp8_;
				_tmp9_ = mark;
				line_mark_update_line_column_cache (_tmp9_);
				_line_mark_unref0 (mark);
			}
		}
	}
}


static gint line_marks_table_compare_line_marks (LineMark** m1, LineMark** m2) {
	gint result = 0;
	gint _tmp0_ = 0;
	LineMark** _tmp1_ = NULL;
	gint _tmp2_ = 0;
	LineMark** _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gint _result_ = 0;
	gint _tmp13_ = 0;
	_tmp1_ = m1;
	_tmp2_ = (*_tmp1_)->line;
	_tmp3_ = m2;
	_tmp4_ = (*_tmp3_)->line;
	if (_tmp2_ == _tmp4_) {
		LineMark** _tmp5_ = NULL;
		gint _tmp6_ = 0;
		LineMark** _tmp7_ = NULL;
		gint _tmp8_ = 0;
		_tmp5_ = m1;
		_tmp6_ = (*_tmp5_)->column;
		_tmp7_ = m2;
		_tmp8_ = (*_tmp7_)->column;
		_tmp0_ = _tmp6_ - _tmp8_;
	} else {
		LineMark** _tmp9_ = NULL;
		gint _tmp10_ = 0;
		LineMark** _tmp11_ = NULL;
		gint _tmp12_ = 0;
		_tmp9_ = m1;
		_tmp10_ = (*_tmp9_)->line;
		_tmp11_ = m2;
		_tmp12_ = (*_tmp11_)->line;
		_tmp0_ = _tmp10_ - _tmp12_;
	}
	_tmp13_ = _tmp0_;
	_result_ = _tmp13_;
	result = _result_;
	return result;
}


static gint _line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a, gconstpointer b, gpointer self) {
	gint result;
	result = line_marks_table_compare_line_marks (a, b);
	return result;
}


static void line_marks_table_sort_line_marks (LineMarksTable* self) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->sorted;
	if (!_tmp0_) {
		LineMark** _tmp1_ = NULL;
		gint _tmp1__length1 = 0;
		LineMark** _tmp2_ = NULL;
		gint _tmp2__length1 = 0;
		line_marks_table_update_line_marks_line_column_cache (self);
		_tmp1_ = self->lineMarks;
		_tmp1__length1 = self->lineMarks_length1;
		_tmp2_ = self->lineMarks;
		_tmp2__length1 = self->lineMarks_length1;
		g_qsort_with_data ((gconstpointer) _tmp1_, _tmp2__length1, (gsize) sizeof (LineMark*), (GCompareDataFunc) _line_marks_table_compare_line_marks_gcompare_data_func, NULL);
		self->priv->sorted = TRUE;
	}
}


static void _vala_array_add1 (LineMark*** array, int* length, int* size, LineMark* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (LineMark*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


void line_marks_table_add_line_mark (LineMarksTable* self, GtkTextMark* textMark, GdkPixbuf* pixbuf) {
	LineMark** _tmp0_ = NULL;
	gint _tmp0__length1 = 0;
	GtkTextMark* _tmp1_ = NULL;
	GdkPixbuf* _tmp2_ = NULL;
	PixbufWithCache* _tmp3_ = NULL;
	PixbufWithCache* _tmp4_ = NULL;
	LineMark* _tmp5_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (textMark != NULL);
	g_return_if_fail (pixbuf != NULL);
	_tmp0_ = self->lineMarks;
	_tmp0__length1 = self->lineMarks_length1;
	_tmp1_ = textMark;
	_tmp2_ = pixbuf;
	_tmp3_ = line_marks_table_get_pixbuf_with_cache (self, _tmp2_);
	_tmp4_ = _tmp3_;
	_tmp5_ = line_mark_new (_tmp1_, _tmp4_);
	_vala_array_add1 (&self->lineMarks, &self->lineMarks_length1, &self->_lineMarks_size_, _tmp5_);
	_pixbuf_with_cache_unref0 (_tmp4_);
	self->priv->sorted = FALSE;
}


void line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self, GtkTextBuffer* buffer, gint line, gint offset, GdkPixbuf* pixbuf) {
	GtkTextIter iter = {0};
	GtkTextBuffer* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	GtkTextIter _tmp3_ = {0};
	GtkTextMark* mark = NULL;
	GtkTextBuffer* _tmp4_ = NULL;
	GtkTextIter _tmp5_ = {0};
	GtkTextMark* _tmp6_ = NULL;
	GtkTextMark* _tmp7_ = NULL;
	GdkPixbuf* _tmp8_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (buffer != NULL);
	g_return_if_fail (pixbuf != NULL);
	_tmp0_ = buffer;
	_tmp1_ = line;
	_tmp2_ = offset;
	gtk_text_buffer_get_iter_at_line_offset (_tmp0_, &_tmp3_, _tmp1_, _tmp2_);
	iter = _tmp3_;
	_tmp4_ = buffer;
	_tmp5_ = iter;
	_tmp6_ = gtk_text_buffer_create_mark (_tmp4_, NULL, &_tmp5_, TRUE);
	_tmp7_ = _g_object_ref0 (_tmp6_);
	mark = _tmp7_;
	_tmp8_ = pixbuf;
	line_marks_table_add_line_mark (self, mark, _tmp8_);
	_g_object_unref0 (mark);
}


static gint line_marks_table_measure_line_height (LineMarksTable* self, GtkSourceView* view) {
	gint result = 0;
	PangoLayout* layout = NULL;
	GtkSourceView* _tmp0_ = NULL;
	PangoLayout* _tmp1_ = NULL;
	gint height = 0;
	PangoLayout* _tmp2_ = NULL;
	gint _tmp5_ = 0;
	gint _tmp6_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (view != NULL, 0);
	_tmp0_ = view;
	_tmp1_ = gtk_widget_create_pango_layout ((GtkWidget*) _tmp0_, "QWERTY");
	layout = _tmp1_;
	height = 12;
	_tmp2_ = layout;
	if (_tmp2_ != NULL) {
		PangoLayout* _tmp3_ = NULL;
		gint _tmp4_ = 0;
		_tmp3_ = layout;
		pango_layout_get_pixel_size (_tmp3_, NULL, &_tmp4_);
		height = _tmp4_;
	}
	_tmp5_ = height;
	self->lineHeight = _tmp5_ - 2;
	_tmp6_ = self->lineHeight;
	result = _tmp6_;
	_g_object_unref0 (layout);
	return result;
}


static gint line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self, GtkTextBuffer* buffer) {
	gint result = 0;
	gint max = 0;
	gint currentLine = 0;
	gint nb = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	max = 0;
	currentLine = -1;
	nb = 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_ = FALSE;
				gint _tmp3_ = 0;
				LineMark** _tmp4_ = NULL;
				gint _tmp4__length1 = 0;
				LineMark* mark = NULL;
				LineMark** _tmp5_ = NULL;
				gint _tmp5__length1 = 0;
				gint _tmp6_ = 0;
				LineMark* _tmp7_ = NULL;
				LineMark* _tmp8_ = NULL;
				GtkTextMark* m = NULL;
				LineMark* _tmp9_ = NULL;
				GtkTextMark* _tmp10_ = NULL;
				GtkTextMark* _tmp11_ = NULL;
				GtkTextMark* _tmp12_ = NULL;
				GtkTextBuffer* _tmp13_ = NULL;
				GtkTextBuffer* _tmp14_ = NULL;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_ = 0;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->lineMarks;
				_tmp4__length1 = self->lineMarks_length1;
				if (!(_tmp3_ < _tmp4__length1)) {
					break;
				}
				_tmp5_ = self->lineMarks;
				_tmp5__length1 = self->lineMarks_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = _line_mark_ref0 (_tmp7_);
				mark = _tmp8_;
				_tmp9_ = mark;
				_tmp10_ = _tmp9_->textMark;
				_tmp11_ = _g_object_ref0 (_tmp10_);
				m = _tmp11_;
				_tmp12_ = m;
				_tmp13_ = gtk_text_mark_get_buffer (_tmp12_);
				_tmp14_ = buffer;
				if (_tmp13_ == _tmp14_) {
					GtkTextIter iter = {0};
					GtkTextBuffer* _tmp15_ = NULL;
					GtkTextMark* _tmp16_ = NULL;
					GtkTextIter _tmp17_ = {0};
					gint _tmp18_ = 0;
					gint _tmp19_ = 0;
					gint _tmp22_ = 0;
					gint _tmp23_ = 0;
					_tmp15_ = buffer;
					_tmp16_ = m;
					gtk_text_buffer_get_iter_at_mark (_tmp15_, &_tmp17_, _tmp16_);
					iter = _tmp17_;
					_tmp18_ = gtk_text_iter_get_line (&iter);
					_tmp19_ = currentLine;
					if (_tmp18_ == _tmp19_) {
						gint _tmp20_ = 0;
						_tmp20_ = nb;
						nb = _tmp20_ + 1;
					} else {
						gint _tmp21_ = 0;
						_tmp21_ = gtk_text_iter_get_line (&iter);
						currentLine = _tmp21_;
						nb = 1;
					}
					_tmp22_ = nb;
					_tmp23_ = max;
					if (_tmp22_ > _tmp23_) {
						gint _tmp24_ = 0;
						_tmp24_ = nb;
						max = _tmp24_;
					}
				}
				_g_object_unref0 (m);
				_line_mark_unref0 (mark);
			}
		}
	}
	result = max;
	return result;
}


static void line_marks_table_size_func (LineMarksTable* self, GtkSourceGutter* gutter, GtkCellRenderer* renderer) {
	GtkSourceView* view = NULL;
	GtkSourceGutter* _tmp0_ = NULL;
	GtkSourceView* _tmp1_ = NULL;
	GtkSourceView* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	GtkTextBuffer* _tmp4_ = NULL;
	gint _tmp5_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	line_marks_table_sort_line_marks (self);
	_tmp0_ = gutter;
	g_object_get (_tmp0_, "view", &_tmp1_, NULL);
	_tmp2_ = _tmp1_;
	view = _tmp2_;
	_tmp3_ = line_marks_table_measure_line_height (self, view);
	_tmp4_ = gtk_text_view_get_buffer ((GtkTextView*) view);
	_tmp5_ = line_marks_table_get_max_nb_marks_on_line (self, _tmp4_);
	self->rendererWidth = _tmp3_ * _tmp5_;
	_g_object_unref0 (self->lastBuffer);
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	_g_object_unref0 (view);
}


static void line_marks_table_data_func (LineMarksTable* self, GtkSourceGutter* gutter, GtkCellRenderer* renderer, gint lineNumber, gboolean currentLine) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	_tmp0_ = lineNumber;
	self->lineNumber = _tmp0_;
}


static void _line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter, GtkCellRenderer* cell, gpointer self) {
	line_marks_table_size_func (self, gutter, cell);
}


static void _line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter, GtkCellRenderer* cell, gint line_number, gboolean current_line, gpointer self) {
	line_marks_table_data_func (self, gutter, cell, line_number, current_line);
}


void line_marks_table_show_in_source_view (LineMarksTable* self, GtkSourceView* sourceView) {
	GtkSourceGutter* gutter = NULL;
	GtkSourceView* _tmp0_ = NULL;
	GtkSourceGutter* _tmp1_ = NULL;
	GtkSourceGutter* _tmp2_ = NULL;
	LineMarksRenderer* renderer = NULL;
	LineMarksRenderer* _tmp3_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sourceView != NULL);
	_tmp0_ = sourceView;
	_tmp1_ = gtk_source_view_get_gutter (_tmp0_, GTK_TEXT_WINDOW_LEFT);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	gutter = _tmp2_;
	_tmp3_ = line_marks_renderer_new (self, gutter);
	g_object_ref_sink (_tmp3_);
	renderer = _tmp3_;
	gtk_source_gutter_insert (gutter, (GtkCellRenderer*) renderer, 0);
	gtk_source_gutter_set_cell_size_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_size_func_gtk_source_gutter_size_func, g_object_ref (self), g_object_unref);
	gtk_source_gutter_set_cell_data_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_data_func_gtk_source_gutter_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (renderer);
	_g_object_unref0 (gutter);
}


LineMarksTable* line_marks_table_construct (GType object_type) {
	LineMarksTable * self = NULL;
	self = (LineMarksTable*) g_object_new (object_type, NULL);
	return self;
}


LineMarksTable* line_marks_table_new (void) {
	return line_marks_table_construct (TYPE_LINE_MARKS_TABLE);
}


static void line_marks_table_class_init (LineMarksTableClass * klass) {
	line_marks_table_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LineMarksTablePrivate));
	G_OBJECT_CLASS (klass)->finalize = line_marks_table_finalize;
}


static void line_marks_table_instance_init (LineMarksTable * self) {
	LineMark** _tmp0_ = NULL;
	self->priv = LINE_MARKS_TABLE_GET_PRIVATE (self);
	_tmp0_ = g_new0 (LineMark*, 0 + 1);
	self->lineMarks = _tmp0_;
	self->lineMarks_length1 = 0;
	self->_lineMarks_size_ = self->lineMarks_length1;
	self->priv->sorted = TRUE;
	self->lineHeight = 0;
	self->rendererWidth = 0;
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	self->lineNumber = -1;
}


static void line_marks_table_finalize (GObject* obj) {
	LineMarksTable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_TABLE, LineMarksTable);
	_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
	self->lineMarks = (_vala_array_free (self->lineMarks, self->lineMarks_length1, (GDestroyNotify) line_mark_unref), NULL);
	_g_object_unref0 (self->lastBuffer);
	G_OBJECT_CLASS (line_marks_table_parent_class)->finalize (obj);
}


GType line_marks_table_get_type (void) {
	static volatile gsize line_marks_table_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_table_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksTableClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_table_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksTable), 0, (GInstanceInitFunc) line_marks_table_instance_init, NULL };
		GType line_marks_table_type_id;
		line_marks_table_type_id = g_type_register_static (G_TYPE_OBJECT, "LineMarksTable", &g_define_type_info, 0);
		g_once_init_leave (&line_marks_table_type_id__volatile, line_marks_table_type_id);
	}
	return line_marks_table_type_id__volatile;
}


LineMarksRenderer* line_marks_renderer_construct (GType object_type, LineMarksTable* table, GtkSourceGutter* gutter) {
	LineMarksRenderer * self = NULL;
	LineMarksTable* _tmp0_ = NULL;
	LineMarksTable* _tmp1_ = NULL;
	GtkSourceGutter* _tmp2_ = NULL;
	GtkSourceGutter* _tmp3_ = NULL;
	g_return_val_if_fail (table != NULL, NULL);
	g_return_val_if_fail (gutter != NULL, NULL);
	self = (LineMarksRenderer*) g_object_new (object_type, NULL);
	_tmp0_ = table;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->table);
	self->priv->table = _tmp1_;
	_tmp2_ = gutter;
	_tmp3_ = _g_object_ref0 (_tmp2_);
	_g_object_unref0 (self->priv->gutter);
	self->priv->gutter = _tmp3_;
	return self;
}


LineMarksRenderer* line_marks_renderer_new (LineMarksTable* table, GtkSourceGutter* gutter) {
	return line_marks_renderer_construct (TYPE_LINE_MARKS_RENDERER, table, gutter);
}


static void line_marks_renderer_real_get_size (GtkCellRenderer* base, GtkWidget* widget, GdkRectangle* cell_area, gint* x_offset, gint* y_offset, gint* width, gint* height) {
	LineMarksRenderer * self;
	gint _vala_x_offset = 0;
	gint _vala_y_offset = 0;
	gint _vala_width = 0;
	gint _vala_height = 0;
	LineMarksTable* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	LineMarksTable* _tmp2_ = NULL;
	gint _tmp3_ = 0;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (widget != NULL);
	_vala_x_offset = 0;
	_vala_y_offset = 0;
	_tmp0_ = self->priv->table;
	_tmp1_ = _tmp0_->rendererWidth;
	_vala_width = _tmp1_;
	_tmp2_ = self->priv->table;
	_tmp3_ = _tmp2_->lineHeight;
	_vala_height = _tmp3_;
	if (x_offset) {
		*x_offset = _vala_x_offset;
	}
	if (y_offset) {
		*y_offset = _vala_y_offset;
	}
	if (width) {
		*width = _vala_width;
	}
	if (height) {
		*height = _vala_height;
	}
}


static void line_marks_renderer_real_render (GtkCellRenderer* base, GdkWindow* window, GtkWidget* widget, GdkRectangle* background_area, GdkRectangle* cell_area, GdkRectangle* expose_area, GtkCellRendererState flags) {
	LineMarksRenderer * self;
	cairo_t* ctx = NULL;
	GdkWindow* _tmp0_ = NULL;
	cairo_t* _tmp1_ = NULL;
	gint x = 0;
	GdkRectangle _tmp2_ = {0};
	gint _tmp3_ = 0;
	GtkTextBuffer* buffer = NULL;
	GtkSourceGutter* _tmp4_ = NULL;
	GtkSourceView* _tmp5_ = NULL;
	GtkSourceView* _tmp6_ = NULL;
	GtkSourceView* _tmp7_ = NULL;
	GtkTextBuffer* _tmp8_ = NULL;
	GtkTextBuffer* _tmp9_ = NULL;
	GtkTextBuffer* _tmp10_ = NULL;
	gboolean _tmp11_ = FALSE;
	LineMarksTable* _tmp12_ = NULL;
	GtkTextBuffer* _tmp13_ = NULL;
	GtkTextBuffer* _tmp14_ = NULL;
	gboolean _tmp19_ = FALSE;
	LineMarksTable* _tmp76_ = NULL;
	LineMarksTable* _tmp77_ = NULL;
	gint _tmp78_ = 0;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (window != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (background_area != NULL);
	g_return_if_fail (cell_area != NULL);
	g_return_if_fail (expose_area != NULL);
	_tmp0_ = window;
	_tmp1_ = gdk_cairo_create ((GdkDrawable*) _tmp0_);
	ctx = _tmp1_;
	_tmp2_ = *background_area;
	_tmp3_ = _tmp2_.x;
	x = _tmp3_;
	_tmp4_ = self->priv->gutter;
	g_object_get (_tmp4_, "view", &_tmp5_, NULL);
	_tmp6_ = _tmp5_;
	_tmp7_ = _tmp6_;
	_tmp8_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp7_);
	_tmp9_ = _g_object_ref0 (_tmp8_);
	_tmp10_ = _tmp9_;
	_g_object_unref0 (_tmp7_);
	buffer = _tmp10_;
	_tmp12_ = self->priv->table;
	_tmp13_ = _tmp12_->lastBuffer;
	_tmp14_ = buffer;
	if (_tmp13_ != _tmp14_) {
		_tmp11_ = TRUE;
	} else {
		LineMarksTable* _tmp15_ = NULL;
		gint _tmp16_ = 0;
		LineMarksTable* _tmp17_ = NULL;
		gint _tmp18_ = 0;
		_tmp15_ = self->priv->table;
		_tmp16_ = _tmp15_->lastLineNumber;
		_tmp17_ = self->priv->table;
		_tmp18_ = _tmp17_->lineNumber;
		_tmp11_ = _tmp16_ >= _tmp18_;
	}
	_tmp19_ = _tmp11_;
	if (_tmp19_) {
		LineMarksTable* _tmp20_ = NULL;
		GtkTextBuffer* _tmp21_ = NULL;
		GtkTextBuffer* _tmp22_ = NULL;
		LineMarksTable* _tmp23_ = NULL;
		_tmp20_ = self->priv->table;
		_tmp21_ = buffer;
		_tmp22_ = _g_object_ref0 (_tmp21_);
		_g_object_unref0 (_tmp20_->lastBuffer);
		_tmp20_->lastBuffer = _tmp22_;
		_tmp23_ = self->priv->table;
		_tmp23_->nextIndex = 0;
	}
	{
		gboolean _tmp24_ = FALSE;
		_tmp24_ = TRUE;
		while (TRUE) {
			gboolean _tmp25_ = FALSE;
			LineMarksTable* _tmp28_ = NULL;
			gint _tmp29_ = 0;
			LineMarksTable* _tmp30_ = NULL;
			LineMark** _tmp31_ = NULL;
			gint _tmp31__length1 = 0;
			LineMark* mark = NULL;
			LineMarksTable* _tmp32_ = NULL;
			LineMark** _tmp33_ = NULL;
			gint _tmp33__length1 = 0;
			LineMarksTable* _tmp34_ = NULL;
			gint _tmp35_ = 0;
			LineMark* _tmp36_ = NULL;
			LineMark* _tmp37_ = NULL;
			GtkTextMark* m = NULL;
			LineMark* _tmp38_ = NULL;
			GtkTextMark* _tmp39_ = NULL;
			GtkTextMark* _tmp40_ = NULL;
			GtkTextMark* _tmp41_ = NULL;
			GtkTextBuffer* _tmp42_ = NULL;
			GtkTextBuffer* _tmp43_ = NULL;
			_tmp25_ = _tmp24_;
			if (!_tmp25_) {
				LineMarksTable* _tmp26_ = NULL;
				gint _tmp27_ = 0;
				_tmp26_ = self->priv->table;
				_tmp27_ = _tmp26_->nextIndex;
				_tmp26_->nextIndex = _tmp27_ + 1;
			}
			_tmp24_ = FALSE;
			_tmp28_ = self->priv->table;
			_tmp29_ = _tmp28_->nextIndex;
			_tmp30_ = self->priv->table;
			_tmp31_ = _tmp30_->lineMarks;
			_tmp31__length1 = _tmp30_->lineMarks_length1;
			if (!(_tmp29_ < _tmp31__length1)) {
				break;
			}
			_tmp32_ = self->priv->table;
			_tmp33_ = _tmp32_->lineMarks;
			_tmp33__length1 = _tmp32_->lineMarks_length1;
			_tmp34_ = self->priv->table;
			_tmp35_ = _tmp34_->nextIndex;
			_tmp36_ = _tmp33_[_tmp35_];
			_tmp37_ = _line_mark_ref0 (_tmp36_);
			mark = _tmp37_;
			_tmp38_ = mark;
			_tmp39_ = _tmp38_->textMark;
			_tmp40_ = _g_object_ref0 (_tmp39_);
			m = _tmp40_;
			_tmp41_ = m;
			_tmp42_ = gtk_text_mark_get_buffer (_tmp41_);
			_tmp43_ = buffer;
			if (_tmp42_ == _tmp43_) {
				GtkTextIter iter = {0};
				GtkTextBuffer* _tmp44_ = NULL;
				GtkTextMark* _tmp45_ = NULL;
				GtkTextIter _tmp46_ = {0};
				gint _tmp47_ = 0;
				LineMarksTable* _tmp48_ = NULL;
				gint _tmp49_ = 0;
				gint _tmp50_ = 0;
				LineMarksTable* _tmp51_ = NULL;
				gint _tmp52_ = 0;
				_tmp44_ = buffer;
				_tmp45_ = m;
				gtk_text_buffer_get_iter_at_mark (_tmp44_, &_tmp46_, _tmp45_);
				iter = _tmp46_;
				_tmp47_ = gtk_text_iter_get_line (&iter);
				_tmp48_ = self->priv->table;
				_tmp49_ = _tmp48_->lineNumber;
				if (_tmp47_ > _tmp49_) {
					_g_object_unref0 (m);
					_line_mark_unref0 (mark);
					break;
				}
				_tmp50_ = gtk_text_iter_get_line (&iter);
				_tmp51_ = self->priv->table;
				_tmp52_ = _tmp51_->lineNumber;
				if (_tmp50_ == _tmp52_) {
					cairo_t* _tmp53_ = NULL;
					gint _tmp54_ = 0;
					GdkRectangle _tmp55_ = {0};
					gint _tmp56_ = 0;
					LineMarksTable* _tmp57_ = NULL;
					gint _tmp58_ = 0;
					LineMarksTable* _tmp59_ = NULL;
					gint _tmp60_ = 0;
					GdkRectangle _tmp61_ = {0};
					cairo_t* _tmp62_ = NULL;
					LineMark* _tmp63_ = NULL;
					PixbufWithCache* _tmp64_ = NULL;
					LineMarksTable* _tmp65_ = NULL;
					gint _tmp66_ = 0;
					GdkPixbuf* _tmp67_ = NULL;
					GdkPixbuf* _tmp68_ = NULL;
					gint _tmp69_ = 0;
					GdkRectangle _tmp70_ = {0};
					gint _tmp71_ = 0;
					cairo_t* _tmp72_ = NULL;
					gint _tmp73_ = 0;
					LineMarksTable* _tmp74_ = NULL;
					gint _tmp75_ = 0;
					_tmp53_ = ctx;
					_tmp54_ = x;
					_tmp55_ = *background_area;
					_tmp56_ = _tmp55_.y;
					_tmp57_ = self->priv->table;
					_tmp58_ = _tmp57_->lineHeight;
					_tmp59_ = self->priv->table;
					_tmp60_ = _tmp59_->lineHeight;
					memset (&_tmp61_, 0, sizeof (GdkRectangle));
					_tmp61_.x = _tmp54_ + 1;
					_tmp61_.y = _tmp56_ + 1;
					_tmp61_.width = _tmp58_ - 2;
					_tmp61_.height = _tmp60_ - 2;
					gdk_cairo_rectangle (_tmp53_, &_tmp61_);
					_tmp62_ = ctx;
					_tmp63_ = mark;
					_tmp64_ = _tmp63_->pixbuf;
					_tmp65_ = self->priv->table;
					_tmp66_ = _tmp65_->lineHeight;
					_tmp67_ = pixbuf_with_cache_get_at_size (_tmp64_, _tmp66_ - 2);
					_tmp68_ = _tmp67_;
					_tmp69_ = x;
					_tmp70_ = *background_area;
					_tmp71_ = _tmp70_.y;
					gdk_cairo_set_source_pixbuf (_tmp62_, _tmp68_, (gdouble) (_tmp69_ + 1), (gdouble) (_tmp71_ + 1));
					_g_object_unref0 (_tmp68_);
					_tmp72_ = ctx;
					cairo_fill (_tmp72_);
					_tmp73_ = x;
					_tmp74_ = self->priv->table;
					_tmp75_ = _tmp74_->lineHeight;
					x = _tmp73_ + _tmp75_;
				}
			}
			_g_object_unref0 (m);
			_line_mark_unref0 (mark);
		}
	}
	_tmp76_ = self->priv->table;
	_tmp77_ = self->priv->table;
	_tmp78_ = _tmp77_->lineNumber;
	_tmp76_->lastLineNumber = _tmp78_;
	_g_object_unref0 (buffer);
	_cairo_destroy0 (ctx);
}


static void line_marks_renderer_class_init (LineMarksRendererClass * klass) {
	line_marks_renderer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LineMarksRendererPrivate));
	GTK_CELL_RENDERER_CLASS (klass)->get_size = line_marks_renderer_real_get_size;
	GTK_CELL_RENDERER_CLASS (klass)->render = line_marks_renderer_real_render;
	G_OBJECT_CLASS (klass)->finalize = line_marks_renderer_finalize;
}


static void line_marks_renderer_instance_init (LineMarksRenderer * self) {
	self->priv = LINE_MARKS_RENDERER_GET_PRIVATE (self);
}


static void line_marks_renderer_finalize (GObject* obj) {
	LineMarksRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_RENDERER, LineMarksRenderer);
	_g_object_unref0 (self->priv->table);
	_g_object_unref0 (self->priv->gutter);
	G_OBJECT_CLASS (line_marks_renderer_parent_class)->finalize (obj);
}


GType line_marks_renderer_get_type (void) {
	static volatile gsize line_marks_renderer_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_renderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksRendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_renderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksRenderer), 0, (GInstanceInitFunc) line_marks_renderer_instance_init, NULL };
		GType line_marks_renderer_type_id;
		line_marks_renderer_type_id = g_type_register_static (GTK_TYPE_CELL_RENDERER, "LineMarksRenderer", &g_define_type_info, 0);
		g_once_init_leave (&line_marks_renderer_type_id__volatile, line_marks_renderer_type_id);
	}
	return line_marks_renderer_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



