/* linemarks.h generated by valac 0.40.4, the Vala compiler, do not modify */


#ifndef __LINEMARKS_H__
#define __LINEMARKS_H__

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtksourceview/gtksourceview.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>

G_BEGIN_DECLS


#define TYPE_LINE_MARKS_TABLE (line_marks_table_get_type ())
#define LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTable))
#define LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))
#define IS_LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_TABLE))
#define IS_LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_TABLE))
#define LINE_MARKS_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))

typedef struct _LineMarksTable LineMarksTable;
typedef struct _LineMarksTableClass LineMarksTableClass;
typedef struct _LineMarksTablePrivate LineMarksTablePrivate;

#define TYPE_LINE_MARK (line_mark_get_type ())
#define LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARK, LineMark))
#define LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARK, LineMarkClass))
#define IS_LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARK))
#define IS_LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARK))
#define LINE_MARK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARK, LineMarkClass))

typedef struct _LineMark LineMark;
typedef struct _LineMarkClass LineMarkClass;

#define TYPE_SOURCE_GUTTER_TEXT_COLUMN (source_gutter_text_column_get_type ())
#define SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumn))
#define SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))
#define IS_SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define IS_SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define SOURCE_GUTTER_TEXT_COLUMN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))

typedef struct _SourceGutterTextColumn SourceGutterTextColumn;
typedef struct _SourceGutterTextColumnClass SourceGutterTextColumnClass;
typedef struct _SourceGutterTextColumnPrivate SourceGutterTextColumnPrivate;

struct _LineMarksTable {
	GObject parent_instance;
	LineMarksTablePrivate * priv;
	LineMark** lineMarks;
	gint lineMarks_length1;
	gint _lineMarks_size_;
	gint lineHeight;
	gint rendererWidth;
	GtkTextBuffer* lastBuffer;
	gint lastLineNumber;
	gint nextIndex;
	gint lineNumber;
};

struct _LineMarksTableClass {
	GObjectClass parent_class;
};

struct _SourceGutterTextColumn {
	GObject parent_instance;
	SourceGutterTextColumnPrivate * priv;
};

struct _SourceGutterTextColumnClass {
	GObjectClass parent_class;
};


GType line_marks_table_get_type (void) G_GNUC_CONST;
gpointer line_mark_ref (gpointer instance);
void line_mark_unref (gpointer instance);
GParamSpec* param_spec_line_mark (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
void value_set_line_mark (GValue* value,
                          gpointer v_object);
void value_take_line_mark (GValue* value,
                           gpointer v_object);
gpointer value_get_line_mark (const GValue* value);
GType line_mark_get_type (void) G_GNUC_CONST;
void line_marks_table_clear (LineMarksTable* self);
void line_marks_table_add_line_mark (LineMarksTable* self,
                                     GtkTextMark* textMark,
                                     GdkPixbuf* pixbuf);
void line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self,
                                                    GtkTextBuffer* buffer,
                                                    gint line,
                                                    gint offset,
                                                    GdkPixbuf* pixbuf);
void line_marks_table_show_in_source_view (LineMarksTable* self,
                                           GtkSourceView* sourceView);
LineMarksTable* line_marks_table_new (void);
LineMarksTable* line_marks_table_construct (GType object_type);
GType source_gutter_text_column_get_type (void) G_GNUC_CONST;
SourceGutterTextColumn* source_gutter_text_column_new (const gchar* sizeText,
                                                       gfloat xalign);
SourceGutterTextColumn* source_gutter_text_column_construct (GType object_type,
                                                             const gchar* sizeText,
                                                             gfloat xalign);
void source_gutter_text_column_clear (SourceGutterTextColumn* self);
void source_gutter_text_column_add_line (SourceGutterTextColumn* self,
                                         const gchar* line);
void source_gutter_text_column_show_in_source_view (SourceGutterTextColumn* self,
                                                    GtkSourceView* sourceView);


G_END_DECLS

#endif
