/* linemarks.c generated by valac 0.40.4, the Vala compiler
 * generated from linemarks.vala, do not modify */



#include <glib.h>
#include <glib-object.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <gtk/gtk.h>
#include <string.h>
#include <gtksourceview/gtksourceview.h>
#include <pango/pango.h>
#include <gdk/gdk.h>
#include <cairo.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <gobject/gvaluecollector.h>


#define TYPE_PIXBUF_WITH_CACHE (pixbuf_with_cache_get_type ())
#define PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCache))
#define PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))
#define IS_PIXBUF_WITH_CACHE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_PIXBUF_WITH_CACHE))
#define IS_PIXBUF_WITH_CACHE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_PIXBUF_WITH_CACHE))
#define PIXBUF_WITH_CACHE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_PIXBUF_WITH_CACHE, PixbufWithCacheClass))

typedef struct _PixbufWithCache PixbufWithCache;
typedef struct _PixbufWithCacheClass PixbufWithCacheClass;
typedef struct _PixbufWithCachePrivate PixbufWithCachePrivate;
#define _pixbuf_with_cache_unref0(var) ((var == NULL) ? NULL : (var = (pixbuf_with_cache_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _ParamSpecPixbufWithCache ParamSpecPixbufWithCache;

#define TYPE_LINE_MARK (line_mark_get_type ())
#define LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARK, LineMark))
#define LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARK, LineMarkClass))
#define IS_LINE_MARK(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARK))
#define IS_LINE_MARK_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARK))
#define LINE_MARK_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARK, LineMarkClass))

typedef struct _LineMark LineMark;
typedef struct _LineMarkClass LineMarkClass;
typedef struct _LineMarkPrivate LineMarkPrivate;
typedef struct _ParamSpecLineMark ParamSpecLineMark;

#define TYPE_LINE_MARKS_TABLE (line_marks_table_get_type ())
#define LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTable))
#define LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))
#define IS_LINE_MARKS_TABLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_TABLE))
#define IS_LINE_MARKS_TABLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_TABLE))
#define LINE_MARKS_TABLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_TABLE, LineMarksTableClass))

typedef struct _LineMarksTable LineMarksTable;
typedef struct _LineMarksTableClass LineMarksTableClass;
typedef struct _LineMarksTablePrivate LineMarksTablePrivate;
enum  {
	LINE_MARKS_TABLE_0_PROPERTY,
	LINE_MARKS_TABLE_NUM_PROPERTIES
};
static GParamSpec* line_marks_table_properties[LINE_MARKS_TABLE_NUM_PROPERTIES];
#define _line_mark_unref0(var) ((var == NULL) ? NULL : (var = (line_mark_unref (var), NULL)))

#define TYPE_LINE_MARKS_RENDERER (line_marks_renderer_get_type ())
#define LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRenderer))
#define LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))
#define IS_LINE_MARKS_RENDERER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_LINE_MARKS_RENDERER))
#define IS_LINE_MARKS_RENDERER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_LINE_MARKS_RENDERER))
#define LINE_MARKS_RENDERER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_LINE_MARKS_RENDERER, LineMarksRendererClass))

typedef struct _LineMarksRenderer LineMarksRenderer;
typedef struct _LineMarksRendererClass LineMarksRendererClass;
typedef struct _LineMarksRendererPrivate LineMarksRendererPrivate;
enum  {
	LINE_MARKS_RENDERER_0_PROPERTY,
	LINE_MARKS_RENDERER_NUM_PROPERTIES
};
static GParamSpec* line_marks_renderer_properties[LINE_MARKS_RENDERER_NUM_PROPERTIES];
#define _cairo_destroy0(var) ((var == NULL) ? NULL : (var = (cairo_destroy (var), NULL)))

#define TYPE_SOURCE_GUTTER_TEXT_COLUMN (source_gutter_text_column_get_type ())
#define SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumn))
#define SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))
#define IS_SOURCE_GUTTER_TEXT_COLUMN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define IS_SOURCE_GUTTER_TEXT_COLUMN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_SOURCE_GUTTER_TEXT_COLUMN))
#define SOURCE_GUTTER_TEXT_COLUMN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnClass))

typedef struct _SourceGutterTextColumn SourceGutterTextColumn;
typedef struct _SourceGutterTextColumnClass SourceGutterTextColumnClass;
typedef struct _SourceGutterTextColumnPrivate SourceGutterTextColumnPrivate;
enum  {
	SOURCE_GUTTER_TEXT_COLUMN_0_PROPERTY,
	SOURCE_GUTTER_TEXT_COLUMN_NUM_PROPERTIES
};
static GParamSpec* source_gutter_text_column_properties[SOURCE_GUTTER_TEXT_COLUMN_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _PixbufWithCache {
	GTypeInstance parent_instance;
	volatile int ref_count;
	PixbufWithCachePrivate * priv;
	PixbufWithCache* next;
	GdkPixbuf* original;
	gint scaledSize;
	GdkPixbuf* scaled;
};

struct _PixbufWithCacheClass {
	GTypeClass parent_class;
	void (*finalize) (PixbufWithCache *self);
};

struct _ParamSpecPixbufWithCache {
	GParamSpec parent_instance;
};

struct _LineMark {
	GTypeInstance parent_instance;
	volatile int ref_count;
	LineMarkPrivate * priv;
	GtkTextMark* textMark;
	PixbufWithCache* pixbuf;
	gint line;
	gint column;
};

struct _LineMarkClass {
	GTypeClass parent_class;
	void (*finalize) (LineMark *self);
};

struct _ParamSpecLineMark {
	GParamSpec parent_instance;
};

struct _LineMarksTable {
	GObject parent_instance;
	LineMarksTablePrivate * priv;
	LineMark** lineMarks;
	gint lineMarks_length1;
	gint _lineMarks_size_;
	gint lineHeight;
	gint rendererWidth;
	GtkTextBuffer* lastBuffer;
	gint lastLineNumber;
	gint nextIndex;
	gint lineNumber;
};

struct _LineMarksTableClass {
	GObjectClass parent_class;
};

struct _LineMarksTablePrivate {
	PixbufWithCache* pixbufCache;
	gboolean sorted;
};

struct _LineMarksRenderer {
	GtkCellRenderer parent_instance;
	LineMarksRendererPrivate * priv;
};

struct _LineMarksRendererClass {
	GtkCellRendererClass parent_class;
};

struct _LineMarksRendererPrivate {
	LineMarksTable* table;
	GtkSourceGutter* gutter;
};

struct _SourceGutterTextColumn {
	GObject parent_instance;
	SourceGutterTextColumnPrivate * priv;
};

struct _SourceGutterTextColumnClass {
	GObjectClass parent_class;
};

struct _SourceGutterTextColumnPrivate {
	gchar* sizeText;
	gchar** lines;
	gint lines_length1;
	gint _lines_size_;
	GtkCellRendererText* renderer;
	GtkSourceGutter** gutters;
	gint gutters_length1;
	gint _gutters_size_;
};


static gpointer pixbuf_with_cache_parent_class = NULL;
static gpointer line_mark_parent_class = NULL;
static gpointer line_marks_table_parent_class = NULL;
static gpointer line_marks_renderer_parent_class = NULL;
static gpointer source_gutter_text_column_parent_class = NULL;

gpointer pixbuf_with_cache_ref (gpointer instance);
void pixbuf_with_cache_unref (gpointer instance);
GParamSpec* param_spec_pixbuf_with_cache (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
void value_set_pixbuf_with_cache (GValue* value,
                                  gpointer v_object);
void value_take_pixbuf_with_cache (GValue* value,
                                   gpointer v_object);
gpointer value_get_pixbuf_with_cache (const GValue* value);
GType pixbuf_with_cache_get_type (void) G_GNUC_CONST;
PixbufWithCache* pixbuf_with_cache_new (PixbufWithCache* next,
                                        GdkPixbuf* original);
PixbufWithCache* pixbuf_with_cache_construct (GType object_type,
                                              PixbufWithCache* next,
                                              GdkPixbuf* original);
GdkPixbuf* pixbuf_with_cache_get_at_size (PixbufWithCache* self,
                                          gint size);
static void pixbuf_with_cache_finalize (PixbufWithCache * obj);
gpointer line_mark_ref (gpointer instance);
void line_mark_unref (gpointer instance);
GParamSpec* param_spec_line_mark (const gchar* name,
                                  const gchar* nick,
                                  const gchar* blurb,
                                  GType object_type,
                                  GParamFlags flags);
void value_set_line_mark (GValue* value,
                          gpointer v_object);
void value_take_line_mark (GValue* value,
                           gpointer v_object);
gpointer value_get_line_mark (const GValue* value);
GType line_mark_get_type (void) G_GNUC_CONST;
LineMark* line_mark_new (GtkTextMark* textMark,
                         PixbufWithCache* pixbuf);
LineMark* line_mark_construct (GType object_type,
                               GtkTextMark* textMark,
                               PixbufWithCache* pixbuf);
void line_mark_update_line_column_cache (LineMark* self);
static void line_mark_finalize (LineMark * obj);
GType line_marks_table_get_type (void) G_GNUC_CONST;
#define LINE_MARKS_TABLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LINE_MARKS_TABLE, LineMarksTablePrivate))
static PixbufWithCache* line_marks_table_get_pixbuf_with_cache (LineMarksTable* self,
                                                         GdkPixbuf* pixbuf);
void line_marks_table_clear (LineMarksTable* self);
static void line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self);
static gint line_marks_table_compare_line_marks (LineMark** m1,
                                          LineMark** m2);
static void line_marks_table_sort_line_marks (LineMarksTable* self);
static gint _line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a,
                                                              gconstpointer b,
                                                              gpointer self);
void line_marks_table_add_line_mark (LineMarksTable* self,
                                     GtkTextMark* textMark,
                                     GdkPixbuf* pixbuf);
static void _vala_array_add1 (LineMark** * array,
                       int* length,
                       int* size,
                       LineMark* value);
void line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self,
                                                    GtkTextBuffer* buffer,
                                                    gint line,
                                                    gint offset,
                                                    GdkPixbuf* pixbuf);
static gint line_marks_table_measure_line_height (LineMarksTable* self,
                                           GtkSourceView* view);
static gint line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self,
                                                GtkTextBuffer* buffer);
static void line_marks_table_size_func (LineMarksTable* self,
                                 GtkSourceGutter* gutter,
                                 GtkCellRenderer* renderer);
static void line_marks_table_data_func (LineMarksTable* self,
                                 GtkSourceGutter* gutter,
                                 GtkCellRenderer* renderer,
                                 gint lineNumber,
                                 gboolean currentLine);
void line_marks_table_show_in_source_view (LineMarksTable* self,
                                           GtkSourceView* sourceView);
GType line_marks_renderer_get_type (void) G_GNUC_CONST;
LineMarksRenderer* line_marks_renderer_new (LineMarksTable* table,
                                            GtkSourceGutter* gutter);
LineMarksRenderer* line_marks_renderer_construct (GType object_type,
                                                  LineMarksTable* table,
                                                  GtkSourceGutter* gutter);
static void _line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                              GtkCellRenderer* cell,
                                                              gpointer self);
static void _line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                              GtkCellRenderer* cell,
                                                              gint line_number,
                                                              gboolean current_line,
                                                              gpointer self);
LineMarksTable* line_marks_table_new (void);
LineMarksTable* line_marks_table_construct (GType object_type);
static void line_marks_table_finalize (GObject * obj);
#define LINE_MARKS_RENDERER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_LINE_MARKS_RENDERER, LineMarksRendererPrivate))
static void line_marks_renderer_real_get_size (GtkCellRenderer* base,
                                        GtkWidget* widget,
                                        GdkRectangle* cell_area,
                                        gint* x_offset,
                                        gint* y_offset,
                                        gint* width,
                                        gint* height);
static void line_marks_renderer_real_render (GtkCellRenderer* base,
                                      GdkWindow* window,
                                      GtkWidget* widget,
                                      GdkRectangle* background_area,
                                      GdkRectangle* cell_area,
                                      GdkRectangle* expose_area,
                                      GtkCellRendererState flags);
static void line_marks_renderer_finalize (GObject * obj);
GType source_gutter_text_column_get_type (void) G_GNUC_CONST;
#define SOURCE_GUTTER_TEXT_COLUMN_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumnPrivate))
SourceGutterTextColumn* source_gutter_text_column_new (const gchar* sizeText,
                                                       gfloat xalign);
SourceGutterTextColumn* source_gutter_text_column_construct (GType object_type,
                                                             const gchar* sizeText,
                                                             gfloat xalign);
void source_gutter_text_column_clear (SourceGutterTextColumn* self);
void source_gutter_text_column_add_line (SourceGutterTextColumn* self,
                                         const gchar* line);
static void _vala_array_add2 (gchar** * array,
                       int* length,
                       int* size,
                       gchar* value);
static void source_gutter_text_column_size_func (SourceGutterTextColumn* self,
                                          GtkSourceGutter* gutter,
                                          GtkCellRenderer* renderer_);
static void source_gutter_text_column_data_func (SourceGutterTextColumn* self,
                                          GtkSourceGutter* gutter,
                                          GtkCellRenderer* renderer_,
                                          gint lineNumber,
                                          gboolean currentLine);
void source_gutter_text_column_show_in_source_view (SourceGutterTextColumn* self,
                                                    GtkSourceView* sourceView);
static void _vala_array_add3 (GtkSourceGutter** * array,
                       int* length,
                       int* size,
                       GtkSourceGutter* value);
static void _source_gutter_text_column_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                                       GtkCellRenderer* cell,
                                                                       gpointer self);
static void _source_gutter_text_column_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                                       GtkCellRenderer* cell,
                                                                       gint line_number,
                                                                       gboolean current_line,
                                                                       gpointer self);
static void source_gutter_text_column_finalize (GObject * obj);
static void _vala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);


static gpointer
_pixbuf_with_cache_ref0 (gpointer self)
{
	return self ? pixbuf_with_cache_ref (self) : NULL;
}


static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}


PixbufWithCache*
pixbuf_with_cache_construct (GType object_type,
                             PixbufWithCache* next,
                             GdkPixbuf* original)
{
	PixbufWithCache* self = NULL;
	PixbufWithCache* _tmp0_;
	GdkPixbuf* _tmp1_;
	g_return_val_if_fail (original != NULL, NULL);
	self = (PixbufWithCache*) g_type_create_instance (object_type);
	_tmp0_ = _pixbuf_with_cache_ref0 (next);
	_pixbuf_with_cache_unref0 (self->next);
	self->next = _tmp0_;
	_tmp1_ = _g_object_ref0 (original);
	_g_object_unref0 (self->original);
	self->original = _tmp1_;
	self->scaledSize = -1;
	_g_object_unref0 (self->scaled);
	self->scaled = NULL;
	return self;
}


PixbufWithCache*
pixbuf_with_cache_new (PixbufWithCache* next,
                       GdkPixbuf* original)
{
	return pixbuf_with_cache_construct (TYPE_PIXBUF_WITH_CACHE, next, original);
}


GdkPixbuf*
pixbuf_with_cache_get_at_size (PixbufWithCache* self,
                               gint size)
{
	GdkPixbuf* result = NULL;
	gint _tmp0_;
	GdkPixbuf* _tmp3_;
	GdkPixbuf* _tmp4_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->scaledSize;
	if (_tmp0_ != size) {
		GdkPixbuf* _tmp1_;
		GdkPixbuf* _tmp2_;
		_tmp1_ = self->original;
		_tmp2_ = gdk_pixbuf_scale_simple (_tmp1_, size, size, GDK_INTERP_BILINEAR);
		_g_object_unref0 (self->scaled);
		self->scaled = _tmp2_;
		self->scaledSize = size;
	}
	_tmp3_ = self->scaled;
	_tmp4_ = _g_object_ref0 (_tmp3_);
	result = _tmp4_;
	return result;
}


static void
value_pixbuf_with_cache_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}


static void
value_pixbuf_with_cache_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		pixbuf_with_cache_unref (value->data[0].v_pointer);
	}
}


static void
value_pixbuf_with_cache_copy_value (const GValue* src_value,
                                    GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = pixbuf_with_cache_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer
value_pixbuf_with_cache_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}


static gchar*
value_pixbuf_with_cache_collect_value (GValue* value,
                                       guint n_collect_values,
                                       GTypeCValue* collect_values,
                                       guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		PixbufWithCache * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = pixbuf_with_cache_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar*
value_pixbuf_with_cache_lcopy_value (const GValue* value,
                                     guint n_collect_values,
                                     GTypeCValue* collect_values,
                                     guint collect_flags)
{
	PixbufWithCache ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = pixbuf_with_cache_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec*
param_spec_pixbuf_with_cache (const gchar* name,
                              const gchar* nick,
                              const gchar* blurb,
                              GType object_type,
                              GParamFlags flags)
{
	ParamSpecPixbufWithCache* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_PIXBUF_WITH_CACHE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer
value_get_pixbuf_with_cache (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE), NULL);
	return value->data[0].v_pointer;
}


void
value_set_pixbuf_with_cache (GValue* value,
                             gpointer v_object)
{
	PixbufWithCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		pixbuf_with_cache_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}


void
value_take_pixbuf_with_cache (GValue* value,
                              gpointer v_object)
{
	PixbufWithCache * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_PIXBUF_WITH_CACHE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_PIXBUF_WITH_CACHE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		pixbuf_with_cache_unref (old);
	}
}


static void
pixbuf_with_cache_class_init (PixbufWithCacheClass * klass)
{
	pixbuf_with_cache_parent_class = g_type_class_peek_parent (klass);
	((PixbufWithCacheClass *) klass)->finalize = pixbuf_with_cache_finalize;
}


static void
pixbuf_with_cache_instance_init (PixbufWithCache * self)
{
	self->ref_count = 1;
}


static void
pixbuf_with_cache_finalize (PixbufWithCache * obj)
{
	PixbufWithCache * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_PIXBUF_WITH_CACHE, PixbufWithCache);
	g_signal_handlers_destroy (self);
	_pixbuf_with_cache_unref0 (self->next);
	_g_object_unref0 (self->original);
	_g_object_unref0 (self->scaled);
}


GType
pixbuf_with_cache_get_type (void)
{
	static volatile gsize pixbuf_with_cache_type_id__volatile = 0;
	if (g_once_init_enter (&pixbuf_with_cache_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_pixbuf_with_cache_init, value_pixbuf_with_cache_free_value, value_pixbuf_with_cache_copy_value, value_pixbuf_with_cache_peek_pointer, "p", value_pixbuf_with_cache_collect_value, "p", value_pixbuf_with_cache_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (PixbufWithCacheClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) pixbuf_with_cache_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (PixbufWithCache), 0, (GInstanceInitFunc) pixbuf_with_cache_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType pixbuf_with_cache_type_id;
		pixbuf_with_cache_type_id = g_type_register_fundamental (g_type_fundamental_next (), "PixbufWithCache", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&pixbuf_with_cache_type_id__volatile, pixbuf_with_cache_type_id);
	}
	return pixbuf_with_cache_type_id__volatile;
}


gpointer
pixbuf_with_cache_ref (gpointer instance)
{
	PixbufWithCache * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void
pixbuf_with_cache_unref (gpointer instance)
{
	PixbufWithCache * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		PIXBUF_WITH_CACHE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


LineMark*
line_mark_construct (GType object_type,
                     GtkTextMark* textMark,
                     PixbufWithCache* pixbuf)
{
	LineMark* self = NULL;
	GtkTextMark* _tmp0_;
	PixbufWithCache* _tmp1_;
	g_return_val_if_fail (textMark != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	self = (LineMark*) g_type_create_instance (object_type);
	_tmp0_ = _g_object_ref0 (textMark);
	_g_object_unref0 (self->textMark);
	self->textMark = _tmp0_;
	_tmp1_ = _pixbuf_with_cache_ref0 (pixbuf);
	_pixbuf_with_cache_unref0 (self->pixbuf);
	self->pixbuf = _tmp1_;
	return self;
}


LineMark*
line_mark_new (GtkTextMark* textMark,
               PixbufWithCache* pixbuf)
{
	return line_mark_construct (TYPE_LINE_MARK, textMark, pixbuf);
}


void
line_mark_update_line_column_cache (LineMark* self)
{
	GtkTextIter iter = {0};
	GtkTextMark* _tmp0_;
	GtkTextBuffer* _tmp1_;
	GtkTextMark* _tmp2_;
	GtkTextIter _tmp3_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->textMark;
	_tmp1_ = gtk_text_mark_get_buffer (_tmp0_);
	_tmp2_ = self->textMark;
	gtk_text_buffer_get_iter_at_mark (_tmp1_, &_tmp3_, _tmp2_);
	iter = _tmp3_;
	self->line = gtk_text_iter_get_line (&iter);
	self->column = gtk_text_iter_get_line_offset (&iter);
}


static void
value_line_mark_init (GValue* value)
{
	value->data[0].v_pointer = NULL;
}


static void
value_line_mark_free_value (GValue* value)
{
	if (value->data[0].v_pointer) {
		line_mark_unref (value->data[0].v_pointer);
	}
}


static void
value_line_mark_copy_value (const GValue* src_value,
                            GValue* dest_value)
{
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = line_mark_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer
value_line_mark_peek_pointer (const GValue* value)
{
	return value->data[0].v_pointer;
}


static gchar*
value_line_mark_collect_value (GValue* value,
                               guint n_collect_values,
                               GTypeCValue* collect_values,
                               guint collect_flags)
{
	if (collect_values[0].v_pointer) {
		LineMark * object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = line_mark_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar*
value_line_mark_lcopy_value (const GValue* value,
                             guint n_collect_values,
                             GTypeCValue* collect_values,
                             guint collect_flags)
{
	LineMark ** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = line_mark_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec*
param_spec_line_mark (const gchar* name,
                      const gchar* nick,
                      const gchar* blurb,
                      GType object_type,
                      GParamFlags flags)
{
	ParamSpecLineMark* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_LINE_MARK), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer
value_get_line_mark (const GValue* value)
{
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK), NULL);
	return value->data[0].v_pointer;
}


void
value_set_line_mark (GValue* value,
                     gpointer v_object)
{
	LineMark * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		line_mark_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}


void
value_take_line_mark (GValue* value,
                      gpointer v_object)
{
	LineMark * old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_LINE_MARK));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_LINE_MARK));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		line_mark_unref (old);
	}
}


static void
line_mark_class_init (LineMarkClass * klass)
{
	line_mark_parent_class = g_type_class_peek_parent (klass);
	((LineMarkClass *) klass)->finalize = line_mark_finalize;
}


static void
line_mark_instance_init (LineMark * self)
{
	self->ref_count = 1;
}


static void
line_mark_finalize (LineMark * obj)
{
	LineMark * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARK, LineMark);
	g_signal_handlers_destroy (self);
	_g_object_unref0 (self->textMark);
	_pixbuf_with_cache_unref0 (self->pixbuf);
}


GType
line_mark_get_type (void)
{
	static volatile gsize line_mark_type_id__volatile = 0;
	if (g_once_init_enter (&line_mark_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_line_mark_init, value_line_mark_free_value, value_line_mark_copy_value, value_line_mark_peek_pointer, "p", value_line_mark_collect_value, "p", value_line_mark_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (LineMarkClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_mark_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMark), 0, (GInstanceInitFunc) line_mark_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType line_mark_type_id;
		line_mark_type_id = g_type_register_fundamental (g_type_fundamental_next (), "LineMark", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&line_mark_type_id__volatile, line_mark_type_id);
	}
	return line_mark_type_id__volatile;
}


gpointer
line_mark_ref (gpointer instance)
{
	LineMark * self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void
line_mark_unref (gpointer instance)
{
	LineMark * self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		LINE_MARK_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static PixbufWithCache*
line_marks_table_get_pixbuf_with_cache (LineMarksTable* self,
                                        GdkPixbuf* pixbuf)
{
	PixbufWithCache* result = NULL;
	PixbufWithCache* cache = NULL;
	PixbufWithCache* _tmp0_;
	PixbufWithCache* _tmp1_;
	PixbufWithCache* _tmp9_;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (pixbuf != NULL, NULL);
	_tmp0_ = self->priv->pixbufCache;
	_tmp1_ = _pixbuf_with_cache_ref0 (_tmp0_);
	cache = _tmp1_;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		PixbufWithCache* _tmp3_;
		PixbufWithCache* _tmp6_;
		PixbufWithCache* _tmp7_;
		PixbufWithCache* _tmp8_;
		_tmp3_ = cache;
		if (_tmp3_ != NULL) {
			PixbufWithCache* _tmp4_;
			GdkPixbuf* _tmp5_;
			_tmp4_ = cache;
			_tmp5_ = _tmp4_->original;
			_tmp2_ = _tmp5_ != pixbuf;
		} else {
			_tmp2_ = FALSE;
		}
		if (!_tmp2_) {
			break;
		}
		_tmp6_ = cache;
		_tmp7_ = _tmp6_->next;
		_tmp8_ = _pixbuf_with_cache_ref0 (_tmp7_);
		_pixbuf_with_cache_unref0 (cache);
		cache = _tmp8_;
	}
	_tmp9_ = cache;
	if (_tmp9_ == NULL) {
		PixbufWithCache* _tmp10_;
		PixbufWithCache* _tmp11_;
		PixbufWithCache* _tmp12_;
		PixbufWithCache* _tmp13_;
		_tmp10_ = self->priv->pixbufCache;
		_tmp11_ = pixbuf_with_cache_new (_tmp10_, pixbuf);
		_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
		self->priv->pixbufCache = _tmp11_;
		_tmp12_ = self->priv->pixbufCache;
		_tmp13_ = _pixbuf_with_cache_ref0 (_tmp12_);
		result = _tmp13_;
		_pixbuf_with_cache_unref0 (cache);
		return result;
	} else {
		result = cache;
		return result;
	}
	_pixbuf_with_cache_unref0 (cache);
}


void
line_marks_table_clear (LineMarksTable* self)
{
	gint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = 0;
	self->lineMarks = g_renew (LineMark*, self->lineMarks, 0);
	(_tmp0_ > self->lineMarks_length1) ? memset (self->lineMarks + self->lineMarks_length1, 0, sizeof (LineMark*) * (_tmp0_ - self->lineMarks_length1)) : NULL;
	self->lineMarks_length1 = _tmp0_;
	self->_lineMarks_size_ = _tmp0_;
}


static gpointer
_line_mark_ref0 (gpointer self)
{
	return self ? line_mark_ref (self) : NULL;
}


static void
line_marks_table_update_line_marks_line_column_cache (LineMarksTable* self)
{
	g_return_if_fail (self != NULL);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				LineMark** _tmp3_;
				gint _tmp3__length1;
				LineMark* mark = NULL;
				LineMark** _tmp4_;
				gint _tmp4__length1;
				gint _tmp5_;
				LineMark* _tmp6_;
				LineMark* _tmp7_;
				LineMark* _tmp8_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = self->lineMarks;
				_tmp3__length1 = self->lineMarks_length1;
				if (!(_tmp2_ < _tmp3__length1)) {
					break;
				}
				_tmp4_ = self->lineMarks;
				_tmp4__length1 = self->lineMarks_length1;
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				_tmp7_ = _line_mark_ref0 (_tmp6_);
				mark = _tmp7_;
				_tmp8_ = mark;
				line_mark_update_line_column_cache (_tmp8_);
				_line_mark_unref0 (mark);
			}
		}
	}
}


static gint
line_marks_table_compare_line_marks (LineMark** m1,
                                     LineMark** m2)
{
	gint result = 0;
	gint _tmp0_ = 0;
	gint _tmp1_;
	gint _tmp2_;
	gint _result_ = 0;
	_tmp1_ = (*m1)->line;
	_tmp2_ = (*m2)->line;
	if (_tmp1_ == _tmp2_) {
		gint _tmp3_;
		gint _tmp4_;
		_tmp3_ = (*m1)->column;
		_tmp4_ = (*m2)->column;
		_tmp0_ = _tmp3_ - _tmp4_;
	} else {
		gint _tmp5_;
		gint _tmp6_;
		_tmp5_ = (*m1)->line;
		_tmp6_ = (*m2)->line;
		_tmp0_ = _tmp5_ - _tmp6_;
	}
	_result_ = _tmp0_;
	result = _result_;
	return result;
}


static gint
_line_marks_table_compare_line_marks_gcompare_data_func (gconstpointer a,
                                                         gconstpointer b,
                                                         gpointer self)
{
	gint result;
	result = line_marks_table_compare_line_marks (a, b);
	return result;
}


static void
line_marks_table_sort_line_marks (LineMarksTable* self)
{
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->sorted;
	if (!_tmp0_) {
		LineMark** _tmp1_;
		gint _tmp1__length1;
		LineMark** _tmp2_;
		gint _tmp2__length1;
		line_marks_table_update_line_marks_line_column_cache (self);
		_tmp1_ = self->lineMarks;
		_tmp1__length1 = self->lineMarks_length1;
		_tmp2_ = self->lineMarks;
		_tmp2__length1 = self->lineMarks_length1;
		g_qsort_with_data ((gconstpointer) _tmp1_, _tmp2__length1, (gsize) sizeof (LineMark*), (GCompareDataFunc) _line_marks_table_compare_line_marks_gcompare_data_func, NULL);
		self->priv->sorted = TRUE;
	}
}


static void
_vala_array_add1 (LineMark** * array,
                  int* length,
                  int* size,
                  LineMark* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (LineMark*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


void
line_marks_table_add_line_mark (LineMarksTable* self,
                                GtkTextMark* textMark,
                                GdkPixbuf* pixbuf)
{
	LineMark** _tmp0_;
	gint _tmp0__length1;
	PixbufWithCache* _tmp1_;
	PixbufWithCache* _tmp2_;
	LineMark* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (textMark != NULL);
	g_return_if_fail (pixbuf != NULL);
	_tmp0_ = self->lineMarks;
	_tmp0__length1 = self->lineMarks_length1;
	_tmp1_ = line_marks_table_get_pixbuf_with_cache (self, pixbuf);
	_tmp2_ = _tmp1_;
	_tmp3_ = line_mark_new (textMark, _tmp2_);
	_vala_array_add1 (&self->lineMarks, &self->lineMarks_length1, &self->_lineMarks_size_, _tmp3_);
	_pixbuf_with_cache_unref0 (_tmp2_);
	self->priv->sorted = FALSE;
}


void
line_marks_table_add_line_mark_at_line_offset (LineMarksTable* self,
                                               GtkTextBuffer* buffer,
                                               gint line,
                                               gint offset,
                                               GdkPixbuf* pixbuf)
{
	GtkTextIter iter = {0};
	GtkTextIter _tmp0_ = {0};
	GtkTextMark* mark = NULL;
	GtkTextIter _tmp1_;
	GtkTextMark* _tmp2_;
	GtkTextMark* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (buffer != NULL);
	g_return_if_fail (pixbuf != NULL);
	gtk_text_buffer_get_iter_at_line_offset (buffer, &_tmp0_, line, offset);
	iter = _tmp0_;
	_tmp1_ = iter;
	_tmp2_ = gtk_text_buffer_create_mark (buffer, NULL, &_tmp1_, TRUE);
	_tmp3_ = _g_object_ref0 (_tmp2_);
	mark = _tmp3_;
	line_marks_table_add_line_mark (self, mark, pixbuf);
	_g_object_unref0 (mark);
}


static gint
line_marks_table_measure_line_height (LineMarksTable* self,
                                      GtkSourceView* view)
{
	gint result = 0;
	PangoLayout* layout = NULL;
	PangoLayout* _tmp0_;
	gint height = 0;
	PangoLayout* _tmp1_;
	gint _tmp4_;
	gint _tmp5_;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (view != NULL, 0);
	_tmp0_ = gtk_widget_create_pango_layout ((GtkWidget*) view, "QWERTY");
	layout = _tmp0_;
	height = 12;
	_tmp1_ = layout;
	if (_tmp1_ != NULL) {
		PangoLayout* _tmp2_;
		gint _tmp3_ = 0;
		_tmp2_ = layout;
		pango_layout_get_pixel_size (_tmp2_, NULL, &_tmp3_);
		height = _tmp3_;
	}
	_tmp4_ = height;
	self->lineHeight = _tmp4_ - 2;
	_tmp5_ = self->lineHeight;
	result = _tmp5_;
	_g_object_unref0 (layout);
	return result;
}


static gint
line_marks_table_get_max_nb_marks_on_line (LineMarksTable* self,
                                           GtkTextBuffer* buffer)
{
	gint result = 0;
	gint max = 0;
	gint currentLine = 0;
	gint nb = 0;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (buffer != NULL, 0);
	max = 0;
	currentLine = -1;
	nb = 0;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp0_ = FALSE;
			_tmp0_ = TRUE;
			while (TRUE) {
				gint _tmp2_;
				LineMark** _tmp3_;
				gint _tmp3__length1;
				LineMark* mark = NULL;
				LineMark** _tmp4_;
				gint _tmp4__length1;
				gint _tmp5_;
				LineMark* _tmp6_;
				LineMark* _tmp7_;
				GtkTextMark* m = NULL;
				LineMark* _tmp8_;
				GtkTextMark* _tmp9_;
				GtkTextMark* _tmp10_;
				GtkTextMark* _tmp11_;
				GtkTextBuffer* _tmp12_;
				if (!_tmp0_) {
					gint _tmp1_;
					_tmp1_ = i;
					i = _tmp1_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp2_ = i;
				_tmp3_ = self->lineMarks;
				_tmp3__length1 = self->lineMarks_length1;
				if (!(_tmp2_ < _tmp3__length1)) {
					break;
				}
				_tmp4_ = self->lineMarks;
				_tmp4__length1 = self->lineMarks_length1;
				_tmp5_ = i;
				_tmp6_ = _tmp4_[_tmp5_];
				_tmp7_ = _line_mark_ref0 (_tmp6_);
				mark = _tmp7_;
				_tmp8_ = mark;
				_tmp9_ = _tmp8_->textMark;
				_tmp10_ = _g_object_ref0 (_tmp9_);
				m = _tmp10_;
				_tmp11_ = m;
				_tmp12_ = gtk_text_mark_get_buffer (_tmp11_);
				if (_tmp12_ == buffer) {
					GtkTextIter iter = {0};
					GtkTextMark* _tmp13_;
					GtkTextIter _tmp14_ = {0};
					gint _tmp15_;
					gint _tmp17_;
					gint _tmp18_;
					_tmp13_ = m;
					gtk_text_buffer_get_iter_at_mark (buffer, &_tmp14_, _tmp13_);
					iter = _tmp14_;
					_tmp15_ = currentLine;
					if (gtk_text_iter_get_line (&iter) == _tmp15_) {
						gint _tmp16_;
						_tmp16_ = nb;
						nb = _tmp16_ + 1;
					} else {
						currentLine = gtk_text_iter_get_line (&iter);
						nb = 1;
					}
					_tmp17_ = nb;
					_tmp18_ = max;
					if (_tmp17_ > _tmp18_) {
						gint _tmp19_;
						_tmp19_ = nb;
						max = _tmp19_;
					}
				}
				_g_object_unref0 (m);
				_line_mark_unref0 (mark);
			}
		}
	}
	result = max;
	return result;
}


static void
line_marks_table_size_func (LineMarksTable* self,
                            GtkSourceGutter* gutter,
                            GtkCellRenderer* renderer)
{
	GtkSourceView* view = NULL;
	GtkSourceView* _tmp0_;
	GtkSourceView* _tmp1_;
	GtkTextBuffer* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	line_marks_table_sort_line_marks (self);
	g_object_get (gutter, "view", &_tmp0_, NULL);
	_tmp1_ = _tmp0_;
	view = _tmp1_;
	_tmp2_ = gtk_text_view_get_buffer ((GtkTextView*) view);
	self->rendererWidth = line_marks_table_measure_line_height (self, view) * line_marks_table_get_max_nb_marks_on_line (self, _tmp2_);
	_g_object_unref0 (self->lastBuffer);
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	_g_object_unref0 (view);
}


static void
line_marks_table_data_func (LineMarksTable* self,
                            GtkSourceGutter* gutter,
                            GtkCellRenderer* renderer,
                            gint lineNumber,
                            gboolean currentLine)
{
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer != NULL);
	self->lineNumber = lineNumber;
}


static void
_line_marks_table_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                         GtkCellRenderer* cell,
                                                         gpointer self)
{
	line_marks_table_size_func ((LineMarksTable*) self, gutter, cell);
}


static void
_line_marks_table_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                         GtkCellRenderer* cell,
                                                         gint line_number,
                                                         gboolean current_line,
                                                         gpointer self)
{
	line_marks_table_data_func ((LineMarksTable*) self, gutter, cell, line_number, current_line);
}


void
line_marks_table_show_in_source_view (LineMarksTable* self,
                                      GtkSourceView* sourceView)
{
	GtkSourceGutter* gutter = NULL;
	GtkSourceGutter* _tmp0_;
	GtkSourceGutter* _tmp1_;
	LineMarksRenderer* renderer = NULL;
	LineMarksRenderer* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sourceView != NULL);
	_tmp0_ = gtk_source_view_get_gutter (sourceView, GTK_TEXT_WINDOW_LEFT);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	gutter = _tmp1_;
	_tmp2_ = line_marks_renderer_new (self, gutter);
	g_object_ref_sink (_tmp2_);
	renderer = _tmp2_;
	gtk_source_gutter_insert (gutter, (GtkCellRenderer*) renderer, 0);
	gtk_source_gutter_set_cell_size_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_size_func_gtk_source_gutter_size_func, g_object_ref (self), g_object_unref);
	gtk_source_gutter_set_cell_data_func (gutter, (GtkCellRenderer*) renderer, _line_marks_table_data_func_gtk_source_gutter_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (renderer);
	_g_object_unref0 (gutter);
}


LineMarksTable*
line_marks_table_construct (GType object_type)
{
	LineMarksTable * self = NULL;
	self = (LineMarksTable*) g_object_new (object_type, NULL);
	return self;
}


LineMarksTable*
line_marks_table_new (void)
{
	return line_marks_table_construct (TYPE_LINE_MARKS_TABLE);
}


static void
line_marks_table_class_init (LineMarksTableClass * klass)
{
	line_marks_table_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LineMarksTablePrivate));
	G_OBJECT_CLASS (klass)->finalize = line_marks_table_finalize;
}


static void
line_marks_table_instance_init (LineMarksTable * self)
{
	LineMark** _tmp0_;
	self->priv = LINE_MARKS_TABLE_GET_PRIVATE (self);
	_tmp0_ = g_new0 (LineMark*, 0 + 1);
	self->lineMarks = _tmp0_;
	self->lineMarks_length1 = 0;
	self->_lineMarks_size_ = self->lineMarks_length1;
	self->priv->sorted = TRUE;
	self->lineHeight = 0;
	self->rendererWidth = 0;
	self->lastBuffer = NULL;
	self->lastLineNumber = -1;
	self->nextIndex = 0;
	self->lineNumber = -1;
}


static void
line_marks_table_finalize (GObject * obj)
{
	LineMarksTable * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_TABLE, LineMarksTable);
	_pixbuf_with_cache_unref0 (self->priv->pixbufCache);
	self->lineMarks = (_vala_array_free (self->lineMarks, self->lineMarks_length1, (GDestroyNotify) line_mark_unref), NULL);
	_g_object_unref0 (self->lastBuffer);
	G_OBJECT_CLASS (line_marks_table_parent_class)->finalize (obj);
}


GType
line_marks_table_get_type (void)
{
	static volatile gsize line_marks_table_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_table_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksTableClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_table_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksTable), 0, (GInstanceInitFunc) line_marks_table_instance_init, NULL };
		GType line_marks_table_type_id;
		line_marks_table_type_id = g_type_register_static (G_TYPE_OBJECT, "LineMarksTable", &g_define_type_info, 0);
		g_once_init_leave (&line_marks_table_type_id__volatile, line_marks_table_type_id);
	}
	return line_marks_table_type_id__volatile;
}


LineMarksRenderer*
line_marks_renderer_construct (GType object_type,
                               LineMarksTable* table,
                               GtkSourceGutter* gutter)
{
	LineMarksRenderer * self = NULL;
	LineMarksTable* _tmp0_;
	GtkSourceGutter* _tmp1_;
	g_return_val_if_fail (table != NULL, NULL);
	g_return_val_if_fail (gutter != NULL, NULL);
	self = (LineMarksRenderer*) g_object_new (object_type, NULL);
	_tmp0_ = _g_object_ref0 (table);
	_g_object_unref0 (self->priv->table);
	self->priv->table = _tmp0_;
	_tmp1_ = _g_object_ref0 (gutter);
	_g_object_unref0 (self->priv->gutter);
	self->priv->gutter = _tmp1_;
	return self;
}


LineMarksRenderer*
line_marks_renderer_new (LineMarksTable* table,
                         GtkSourceGutter* gutter)
{
	return line_marks_renderer_construct (TYPE_LINE_MARKS_RENDERER, table, gutter);
}


static void
line_marks_renderer_real_get_size (GtkCellRenderer* base,
                                   GtkWidget* widget,
                                   GdkRectangle* cell_area,
                                   gint* x_offset,
                                   gint* y_offset,
                                   gint* width,
                                   gint* height)
{
	LineMarksRenderer * self;
	gint _vala_x_offset = 0;
	gint _vala_y_offset = 0;
	gint _vala_width = 0;
	gint _vala_height = 0;
	LineMarksTable* _tmp0_;
	gint _tmp1_;
	LineMarksTable* _tmp2_;
	gint _tmp3_;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (widget != NULL);
	_vala_x_offset = 0;
	_vala_y_offset = 0;
	_tmp0_ = self->priv->table;
	_tmp1_ = _tmp0_->rendererWidth;
	_vala_width = _tmp1_;
	_tmp2_ = self->priv->table;
	_tmp3_ = _tmp2_->lineHeight;
	_vala_height = _tmp3_;
	if (x_offset) {
		*x_offset = _vala_x_offset;
	}
	if (y_offset) {
		*y_offset = _vala_y_offset;
	}
	if (width) {
		*width = _vala_width;
	}
	if (height) {
		*height = _vala_height;
	}
}


static void
line_marks_renderer_real_render (GtkCellRenderer* base,
                                 GdkWindow* window,
                                 GtkWidget* widget,
                                 GdkRectangle* background_area,
                                 GdkRectangle* cell_area,
                                 GdkRectangle* expose_area,
                                 GtkCellRendererState flags)
{
	LineMarksRenderer * self;
	cairo_t* ctx = NULL;
	cairo_t* _tmp0_;
	gint x = 0;
	GdkRectangle _tmp1_;
	gint _tmp2_;
	GtkTextBuffer* buffer = NULL;
	GtkSourceGutter* _tmp3_;
	GtkSourceView* _tmp4_;
	GtkSourceView* _tmp5_;
	GtkSourceView* _tmp6_;
	GtkTextBuffer* _tmp7_;
	GtkTextBuffer* _tmp8_;
	GtkTextBuffer* _tmp9_;
	gboolean _tmp10_ = FALSE;
	LineMarksTable* _tmp11_;
	GtkTextBuffer* _tmp12_;
	GtkTextBuffer* _tmp13_;
	LineMarksTable* _tmp71_;
	LineMarksTable* _tmp72_;
	gint _tmp73_;
	self = (LineMarksRenderer*) base;
	g_return_if_fail (window != NULL);
	g_return_if_fail (widget != NULL);
	g_return_if_fail (background_area != NULL);
	g_return_if_fail (cell_area != NULL);
	g_return_if_fail (expose_area != NULL);
	_tmp0_ = gdk_cairo_create ((GdkDrawable*) window);
	ctx = _tmp0_;
	_tmp1_ = *background_area;
	_tmp2_ = _tmp1_.x;
	x = _tmp2_;
	_tmp3_ = self->priv->gutter;
	g_object_get (_tmp3_, "view", &_tmp4_, NULL);
	_tmp5_ = _tmp4_;
	_tmp6_ = _tmp5_;
	_tmp7_ = gtk_text_view_get_buffer ((GtkTextView*) _tmp6_);
	_tmp8_ = _g_object_ref0 (_tmp7_);
	_tmp9_ = _tmp8_;
	_g_object_unref0 (_tmp6_);
	buffer = _tmp9_;
	_tmp11_ = self->priv->table;
	_tmp12_ = _tmp11_->lastBuffer;
	_tmp13_ = buffer;
	if (_tmp12_ != _tmp13_) {
		_tmp10_ = TRUE;
	} else {
		LineMarksTable* _tmp14_;
		gint _tmp15_;
		LineMarksTable* _tmp16_;
		gint _tmp17_;
		_tmp14_ = self->priv->table;
		_tmp15_ = _tmp14_->lastLineNumber;
		_tmp16_ = self->priv->table;
		_tmp17_ = _tmp16_->lineNumber;
		_tmp10_ = _tmp15_ >= _tmp17_;
	}
	if (_tmp10_) {
		LineMarksTable* _tmp18_;
		GtkTextBuffer* _tmp19_;
		GtkTextBuffer* _tmp20_;
		LineMarksTable* _tmp21_;
		_tmp18_ = self->priv->table;
		_tmp19_ = buffer;
		_tmp20_ = _g_object_ref0 (_tmp19_);
		_g_object_unref0 (_tmp18_->lastBuffer);
		_tmp18_->lastBuffer = _tmp20_;
		_tmp21_ = self->priv->table;
		_tmp21_->nextIndex = 0;
	}
	{
		gboolean _tmp22_ = FALSE;
		_tmp22_ = TRUE;
		while (TRUE) {
			LineMarksTable* _tmp25_;
			gint _tmp26_;
			LineMarksTable* _tmp27_;
			LineMark** _tmp28_;
			gint _tmp28__length1;
			LineMark* mark = NULL;
			LineMarksTable* _tmp29_;
			LineMark** _tmp30_;
			gint _tmp30__length1;
			LineMarksTable* _tmp31_;
			gint _tmp32_;
			LineMark* _tmp33_;
			LineMark* _tmp34_;
			GtkTextMark* m = NULL;
			LineMark* _tmp35_;
			GtkTextMark* _tmp36_;
			GtkTextMark* _tmp37_;
			GtkTextMark* _tmp38_;
			GtkTextBuffer* _tmp39_;
			GtkTextBuffer* _tmp40_;
			if (!_tmp22_) {
				LineMarksTable* _tmp23_;
				gint _tmp24_;
				_tmp23_ = self->priv->table;
				_tmp24_ = _tmp23_->nextIndex;
				_tmp23_->nextIndex = _tmp24_ + 1;
			}
			_tmp22_ = FALSE;
			_tmp25_ = self->priv->table;
			_tmp26_ = _tmp25_->nextIndex;
			_tmp27_ = self->priv->table;
			_tmp28_ = _tmp27_->lineMarks;
			_tmp28__length1 = _tmp27_->lineMarks_length1;
			if (!(_tmp26_ < _tmp28__length1)) {
				break;
			}
			_tmp29_ = self->priv->table;
			_tmp30_ = _tmp29_->lineMarks;
			_tmp30__length1 = _tmp29_->lineMarks_length1;
			_tmp31_ = self->priv->table;
			_tmp32_ = _tmp31_->nextIndex;
			_tmp33_ = _tmp30_[_tmp32_];
			_tmp34_ = _line_mark_ref0 (_tmp33_);
			mark = _tmp34_;
			_tmp35_ = mark;
			_tmp36_ = _tmp35_->textMark;
			_tmp37_ = _g_object_ref0 (_tmp36_);
			m = _tmp37_;
			_tmp38_ = m;
			_tmp39_ = gtk_text_mark_get_buffer (_tmp38_);
			_tmp40_ = buffer;
			if (_tmp39_ == _tmp40_) {
				GtkTextIter iter = {0};
				GtkTextBuffer* _tmp41_;
				GtkTextMark* _tmp42_;
				GtkTextIter _tmp43_ = {0};
				LineMarksTable* _tmp44_;
				gint _tmp45_;
				LineMarksTable* _tmp46_;
				gint _tmp47_;
				_tmp41_ = buffer;
				_tmp42_ = m;
				gtk_text_buffer_get_iter_at_mark (_tmp41_, &_tmp43_, _tmp42_);
				iter = _tmp43_;
				_tmp44_ = self->priv->table;
				_tmp45_ = _tmp44_->lineNumber;
				if (gtk_text_iter_get_line (&iter) > _tmp45_) {
					_g_object_unref0 (m);
					_line_mark_unref0 (mark);
					break;
				}
				_tmp46_ = self->priv->table;
				_tmp47_ = _tmp46_->lineNumber;
				if (gtk_text_iter_get_line (&iter) == _tmp47_) {
					cairo_t* _tmp48_;
					gint _tmp49_;
					GdkRectangle _tmp50_;
					gint _tmp51_;
					LineMarksTable* _tmp52_;
					gint _tmp53_;
					LineMarksTable* _tmp54_;
					gint _tmp55_;
					GdkRectangle _tmp56_ = {0};
					cairo_t* _tmp57_;
					LineMark* _tmp58_;
					PixbufWithCache* _tmp59_;
					LineMarksTable* _tmp60_;
					gint _tmp61_;
					GdkPixbuf* _tmp62_;
					GdkPixbuf* _tmp63_;
					gint _tmp64_;
					GdkRectangle _tmp65_;
					gint _tmp66_;
					cairo_t* _tmp67_;
					gint _tmp68_;
					LineMarksTable* _tmp69_;
					gint _tmp70_;
					_tmp48_ = ctx;
					_tmp49_ = x;
					_tmp50_ = *background_area;
					_tmp51_ = _tmp50_.y;
					_tmp52_ = self->priv->table;
					_tmp53_ = _tmp52_->lineHeight;
					_tmp54_ = self->priv->table;
					_tmp55_ = _tmp54_->lineHeight;
					memset (&_tmp56_, 0, sizeof (GdkRectangle));
					_tmp56_.x = _tmp49_ + 1;
					_tmp56_.y = _tmp51_ + 1;
					_tmp56_.width = _tmp53_ - 2;
					_tmp56_.height = _tmp55_ - 2;
					gdk_cairo_rectangle (_tmp48_, &_tmp56_);
					_tmp57_ = ctx;
					_tmp58_ = mark;
					_tmp59_ = _tmp58_->pixbuf;
					_tmp60_ = self->priv->table;
					_tmp61_ = _tmp60_->lineHeight;
					_tmp62_ = pixbuf_with_cache_get_at_size (_tmp59_, _tmp61_ - 2);
					_tmp63_ = _tmp62_;
					_tmp64_ = x;
					_tmp65_ = *background_area;
					_tmp66_ = _tmp65_.y;
					gdk_cairo_set_source_pixbuf (_tmp57_, _tmp63_, (gdouble) (_tmp64_ + 1), (gdouble) (_tmp66_ + 1));
					_g_object_unref0 (_tmp63_);
					_tmp67_ = ctx;
					cairo_fill (_tmp67_);
					_tmp68_ = x;
					_tmp69_ = self->priv->table;
					_tmp70_ = _tmp69_->lineHeight;
					x = _tmp68_ + _tmp70_;
				}
			}
			_g_object_unref0 (m);
			_line_mark_unref0 (mark);
		}
	}
	_tmp71_ = self->priv->table;
	_tmp72_ = self->priv->table;
	_tmp73_ = _tmp72_->lineNumber;
	_tmp71_->lastLineNumber = _tmp73_;
	_g_object_unref0 (buffer);
	_cairo_destroy0 (ctx);
}


static void
line_marks_renderer_class_init (LineMarksRendererClass * klass)
{
	line_marks_renderer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (LineMarksRendererPrivate));
	((GtkCellRendererClass *) klass)->get_size = (void (*) (GtkCellRenderer *, GtkWidget*, GdkRectangle*, gint*, gint*, gint*, gint*)) line_marks_renderer_real_get_size;
	((GtkCellRendererClass *) klass)->render = (void (*) (GtkCellRenderer *, GdkWindow*, GtkWidget*, GdkRectangle*, GdkRectangle*, GdkRectangle*, GtkCellRendererState)) line_marks_renderer_real_render;
	G_OBJECT_CLASS (klass)->finalize = line_marks_renderer_finalize;
}


static void
line_marks_renderer_instance_init (LineMarksRenderer * self)
{
	self->priv = LINE_MARKS_RENDERER_GET_PRIVATE (self);
}


static void
line_marks_renderer_finalize (GObject * obj)
{
	LineMarksRenderer * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_LINE_MARKS_RENDERER, LineMarksRenderer);
	_g_object_unref0 (self->priv->table);
	_g_object_unref0 (self->priv->gutter);
	G_OBJECT_CLASS (line_marks_renderer_parent_class)->finalize (obj);
}


GType
line_marks_renderer_get_type (void)
{
	static volatile gsize line_marks_renderer_type_id__volatile = 0;
	if (g_once_init_enter (&line_marks_renderer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (LineMarksRendererClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) line_marks_renderer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (LineMarksRenderer), 0, (GInstanceInitFunc) line_marks_renderer_instance_init, NULL };
		GType line_marks_renderer_type_id;
		line_marks_renderer_type_id = g_type_register_static (GTK_TYPE_CELL_RENDERER, "LineMarksRenderer", &g_define_type_info, 0);
		g_once_init_leave (&line_marks_renderer_type_id__volatile, line_marks_renderer_type_id);
	}
	return line_marks_renderer_type_id__volatile;
}


SourceGutterTextColumn*
source_gutter_text_column_construct (GType object_type,
                                     const gchar* sizeText,
                                     gfloat xalign)
{
	SourceGutterTextColumn * self = NULL;
	gchar* _tmp0_;
	GtkCellRendererText* _tmp1_;
	GtkCellRendererText* _tmp2_;
	g_return_val_if_fail (sizeText != NULL, NULL);
	self = (SourceGutterTextColumn*) g_object_new (object_type, NULL);
	_tmp0_ = g_strdup (sizeText);
	_g_free0 (self->priv->sizeText);
	self->priv->sizeText = _tmp0_;
	_tmp1_ = (GtkCellRendererText*) gtk_cell_renderer_text_new ();
	g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->priv->renderer);
	self->priv->renderer = _tmp1_;
	_tmp2_ = self->priv->renderer;
	g_object_set ((GtkCellRenderer*) _tmp2_, "xalign", xalign, NULL);
	return self;
}


SourceGutterTextColumn*
source_gutter_text_column_new (const gchar* sizeText,
                               gfloat xalign)
{
	return source_gutter_text_column_construct (TYPE_SOURCE_GUTTER_TEXT_COLUMN, sizeText, xalign);
}


void
source_gutter_text_column_clear (SourceGutterTextColumn* self)
{
	gchar** _tmp0_;
	GtkSourceGutter** _tmp1_;
	gint _tmp1__length1;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	self->priv->lines = (_vala_array_free (self->priv->lines, self->priv->lines_length1, (GDestroyNotify) g_free), NULL);
	self->priv->lines = _tmp0_;
	self->priv->lines_length1 = 0;
	self->priv->_lines_size_ = self->priv->lines_length1;
	_tmp1_ = self->priv->gutters;
	_tmp1__length1 = self->priv->gutters_length1;
	{
		GtkSourceGutter** gutter_collection = NULL;
		gint gutter_collection_length1 = 0;
		gint _gutter_collection_size_ = 0;
		gint gutter_it = 0;
		gutter_collection = _tmp1_;
		gutter_collection_length1 = _tmp1__length1;
		for (gutter_it = 0; gutter_it < _tmp1__length1; gutter_it = gutter_it + 1) {
			GtkSourceGutter* _tmp2_;
			GtkSourceGutter* gutter = NULL;
			_tmp2_ = _g_object_ref0 (gutter_collection[gutter_it]);
			gutter = _tmp2_;
			{
				GtkSourceGutter* _tmp3_;
				_tmp3_ = gutter;
				gtk_source_gutter_queue_draw (_tmp3_);
				_g_object_unref0 (gutter);
			}
		}
	}
}


static void
_vala_array_add2 (gchar** * array,
                  int* length,
                  int* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


void
source_gutter_text_column_add_line (SourceGutterTextColumn* self,
                                    const gchar* line)
{
	gchar** _tmp0_;
	gint _tmp0__length1;
	gchar* _tmp1_;
	GtkSourceGutter** _tmp2_;
	gint _tmp2__length1;
	g_return_if_fail (self != NULL);
	g_return_if_fail (line != NULL);
	_tmp0_ = self->priv->lines;
	_tmp0__length1 = self->priv->lines_length1;
	_tmp1_ = g_strdup (line);
	_vala_array_add2 (&self->priv->lines, &self->priv->lines_length1, &self->priv->_lines_size_, _tmp1_);
	_tmp2_ = self->priv->gutters;
	_tmp2__length1 = self->priv->gutters_length1;
	{
		GtkSourceGutter** gutter_collection = NULL;
		gint gutter_collection_length1 = 0;
		gint _gutter_collection_size_ = 0;
		gint gutter_it = 0;
		gutter_collection = _tmp2_;
		gutter_collection_length1 = _tmp2__length1;
		for (gutter_it = 0; gutter_it < _tmp2__length1; gutter_it = gutter_it + 1) {
			GtkSourceGutter* _tmp3_;
			GtkSourceGutter* gutter = NULL;
			_tmp3_ = _g_object_ref0 (gutter_collection[gutter_it]);
			gutter = _tmp3_;
			{
				GtkSourceGutter* _tmp4_;
				_tmp4_ = gutter;
				gtk_source_gutter_queue_draw (_tmp4_);
				_g_object_unref0 (gutter);
			}
		}
	}
}


static void
source_gutter_text_column_size_func (SourceGutterTextColumn* self,
                                     GtkSourceGutter* gutter,
                                     GtkCellRenderer* renderer_)
{
	GtkCellRendererText* _tmp0_;
	const gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer_ != NULL);
	_tmp0_ = self->priv->renderer;
	_tmp1_ = self->priv->sizeText;
	g_object_set (_tmp0_, "text", _tmp1_, NULL);
}


static void
source_gutter_text_column_data_func (SourceGutterTextColumn* self,
                                     GtkSourceGutter* gutter,
                                     GtkCellRenderer* renderer_,
                                     gint lineNumber,
                                     gboolean currentLine)
{
	const gchar* _tmp0_ = NULL;
	gchar** _tmp1_;
	gint _tmp1__length1;
	GtkCellRendererText* _tmp4_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (gutter != NULL);
	g_return_if_fail (renderer_ != NULL);
	_tmp1_ = self->priv->lines;
	_tmp1__length1 = self->priv->lines_length1;
	if (lineNumber < _tmp1__length1) {
		gchar** _tmp2_;
		gint _tmp2__length1;
		const gchar* _tmp3_;
		_tmp2_ = self->priv->lines;
		_tmp2__length1 = self->priv->lines_length1;
		_tmp3_ = _tmp2_[lineNumber];
		_tmp0_ = _tmp3_;
	} else {
		_tmp0_ = "";
	}
	_tmp4_ = self->priv->renderer;
	g_object_set (_tmp4_, "text", _tmp0_, NULL);
}


static void
_vala_array_add3 (GtkSourceGutter** * array,
                  int* length,
                  int* size,
                  GtkSourceGutter* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (GtkSourceGutter*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static void
_source_gutter_text_column_size_func_gtk_source_gutter_size_func (GtkSourceGutter* gutter,
                                                                  GtkCellRenderer* cell,
                                                                  gpointer self)
{
	source_gutter_text_column_size_func ((SourceGutterTextColumn*) self, gutter, cell);
}


static void
_source_gutter_text_column_data_func_gtk_source_gutter_data_func (GtkSourceGutter* gutter,
                                                                  GtkCellRenderer* cell,
                                                                  gint line_number,
                                                                  gboolean current_line,
                                                                  gpointer self)
{
	source_gutter_text_column_data_func ((SourceGutterTextColumn*) self, gutter, cell, line_number, current_line);
}


void
source_gutter_text_column_show_in_source_view (SourceGutterTextColumn* self,
                                               GtkSourceView* sourceView)
{
	GtkSourceGutter* gutter = NULL;
	GtkSourceGutter* _tmp0_;
	GtkSourceGutter* _tmp1_;
	GtkSourceGutter** _tmp2_;
	gint _tmp2__length1;
	GtkSourceGutter* _tmp3_;
	GtkCellRendererText* _tmp4_;
	GtkCellRendererText* _tmp5_;
	GtkCellRendererText* _tmp6_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (sourceView != NULL);
	_tmp0_ = gtk_source_view_get_gutter (sourceView, GTK_TEXT_WINDOW_LEFT);
	_tmp1_ = _g_object_ref0 (_tmp0_);
	gutter = _tmp1_;
	_tmp2_ = self->priv->gutters;
	_tmp2__length1 = self->priv->gutters_length1;
	_tmp3_ = _g_object_ref0 (gutter);
	_vala_array_add3 (&self->priv->gutters, &self->priv->gutters_length1, &self->priv->_gutters_size_, _tmp3_);
	_tmp4_ = self->priv->renderer;
	gtk_source_gutter_insert (gutter, (GtkCellRenderer*) _tmp4_, -5);
	_tmp5_ = self->priv->renderer;
	gtk_source_gutter_set_cell_size_func (gutter, (GtkCellRenderer*) _tmp5_, _source_gutter_text_column_size_func_gtk_source_gutter_size_func, g_object_ref (self), g_object_unref);
	_tmp6_ = self->priv->renderer;
	gtk_source_gutter_set_cell_data_func (gutter, (GtkCellRenderer*) _tmp6_, _source_gutter_text_column_data_func_gtk_source_gutter_data_func, g_object_ref (self), g_object_unref);
	_g_object_unref0 (gutter);
}


static void
source_gutter_text_column_class_init (SourceGutterTextColumnClass * klass)
{
	source_gutter_text_column_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (SourceGutterTextColumnPrivate));
	G_OBJECT_CLASS (klass)->finalize = source_gutter_text_column_finalize;
}


static void
source_gutter_text_column_instance_init (SourceGutterTextColumn * self)
{
	gchar** _tmp0_;
	self->priv = SOURCE_GUTTER_TEXT_COLUMN_GET_PRIVATE (self);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	self->priv->lines = _tmp0_;
	self->priv->lines_length1 = 0;
	self->priv->_lines_size_ = self->priv->lines_length1;
}


static void
source_gutter_text_column_finalize (GObject * obj)
{
	SourceGutterTextColumn * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_SOURCE_GUTTER_TEXT_COLUMN, SourceGutterTextColumn);
	_g_free0 (self->priv->sizeText);
	self->priv->lines = (_vala_array_free (self->priv->lines, self->priv->lines_length1, (GDestroyNotify) g_free), NULL);
	_g_object_unref0 (self->priv->renderer);
	self->priv->gutters = (_vala_array_free (self->priv->gutters, self->priv->gutters_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (source_gutter_text_column_parent_class)->finalize (obj);
}


GType
source_gutter_text_column_get_type (void)
{
	static volatile gsize source_gutter_text_column_type_id__volatile = 0;
	if (g_once_init_enter (&source_gutter_text_column_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (SourceGutterTextColumnClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) source_gutter_text_column_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SourceGutterTextColumn), 0, (GInstanceInitFunc) source_gutter_text_column_instance_init, NULL };
		GType source_gutter_text_column_type_id;
		source_gutter_text_column_type_id = g_type_register_static (G_TYPE_OBJECT, "SourceGutterTextColumn", &g_define_type_info, 0);
		g_once_init_leave (&source_gutter_text_column_type_id__volatile, source_gutter_text_column_type_id);
	}
	return source_gutter_text_column_type_id__volatile;
}


static void
_vala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void
_vala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



